// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package railway

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// BuildLogsQueryBuildLogsLog includes the requested fields of the GraphQL type Log.
// The GraphQL type's documentation follows.
//
// The result of a logs query.
type BuildLogsQueryBuildLogsLog struct {
	// The timestamp of the log message in format RFC3339 (nano)
	Timestamp string `json:"timestamp"`
	// The contents of the log message
	Message string `json:"message"`
	// The severity of the log message (eg. err)
	Severity *string `json:"severity"`
	// The attributes that were parsed from a structured log
	Attributes []BuildLogsQueryBuildLogsLogAttributesLogAttribute `json:"attributes"`
	// The tags that were associated with the log
	Tags *BuildLogsQueryBuildLogsLogTags `json:"tags"`
}

// GetTimestamp returns BuildLogsQueryBuildLogsLog.Timestamp, and is useful for accessing the field via an interface.
func (v *BuildLogsQueryBuildLogsLog) GetTimestamp() string { return v.Timestamp }

// GetMessage returns BuildLogsQueryBuildLogsLog.Message, and is useful for accessing the field via an interface.
func (v *BuildLogsQueryBuildLogsLog) GetMessage() string { return v.Message }

// GetSeverity returns BuildLogsQueryBuildLogsLog.Severity, and is useful for accessing the field via an interface.
func (v *BuildLogsQueryBuildLogsLog) GetSeverity() *string { return v.Severity }

// GetAttributes returns BuildLogsQueryBuildLogsLog.Attributes, and is useful for accessing the field via an interface.
func (v *BuildLogsQueryBuildLogsLog) GetAttributes() []BuildLogsQueryBuildLogsLogAttributesLogAttribute {
	return v.Attributes
}

// GetTags returns BuildLogsQueryBuildLogsLog.Tags, and is useful for accessing the field via an interface.
func (v *BuildLogsQueryBuildLogsLog) GetTags() *BuildLogsQueryBuildLogsLogTags { return v.Tags }

// BuildLogsQueryBuildLogsLogAttributesLogAttribute includes the requested fields of the GraphQL type LogAttribute.
// The GraphQL type's documentation follows.
//
// The attributes associated with a structured log
type BuildLogsQueryBuildLogsLogAttributesLogAttribute struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// GetKey returns BuildLogsQueryBuildLogsLogAttributesLogAttribute.Key, and is useful for accessing the field via an interface.
func (v *BuildLogsQueryBuildLogsLogAttributesLogAttribute) GetKey() string { return v.Key }

// GetValue returns BuildLogsQueryBuildLogsLogAttributesLogAttribute.Value, and is useful for accessing the field via an interface.
func (v *BuildLogsQueryBuildLogsLogAttributesLogAttribute) GetValue() string { return v.Value }

// BuildLogsQueryBuildLogsLogTags includes the requested fields of the GraphQL type LogTags.
// The GraphQL type's documentation follows.
//
// The tags associated with a specific log
type BuildLogsQueryBuildLogsLogTags struct {
	DeploymentId         *string `json:"deploymentId"`
	DeploymentInstanceId *string `json:"deploymentInstanceId"`
	ServiceId            *string `json:"serviceId"`
	ProjectId            *string `json:"projectId"`
	EnvironmentId        *string `json:"environmentId"`
}

// GetDeploymentId returns BuildLogsQueryBuildLogsLogTags.DeploymentId, and is useful for accessing the field via an interface.
func (v *BuildLogsQueryBuildLogsLogTags) GetDeploymentId() *string { return v.DeploymentId }

// GetDeploymentInstanceId returns BuildLogsQueryBuildLogsLogTags.DeploymentInstanceId, and is useful for accessing the field via an interface.
func (v *BuildLogsQueryBuildLogsLogTags) GetDeploymentInstanceId() *string {
	return v.DeploymentInstanceId
}

// GetServiceId returns BuildLogsQueryBuildLogsLogTags.ServiceId, and is useful for accessing the field via an interface.
func (v *BuildLogsQueryBuildLogsLogTags) GetServiceId() *string { return v.ServiceId }

// GetProjectId returns BuildLogsQueryBuildLogsLogTags.ProjectId, and is useful for accessing the field via an interface.
func (v *BuildLogsQueryBuildLogsLogTags) GetProjectId() *string { return v.ProjectId }

// GetEnvironmentId returns BuildLogsQueryBuildLogsLogTags.EnvironmentId, and is useful for accessing the field via an interface.
func (v *BuildLogsQueryBuildLogsLogTags) GetEnvironmentId() *string { return v.EnvironmentId }

// BuildLogsQueryResponse is returned by BuildLogsQuery on success.
type BuildLogsQueryResponse struct {
	// Fetch logs for a build
	BuildLogs []BuildLogsQueryBuildLogsLog `json:"buildLogs"`
}

// GetBuildLogs returns BuildLogsQueryResponse.BuildLogs, and is useful for accessing the field via an interface.
func (v *BuildLogsQueryResponse) GetBuildLogs() []BuildLogsQueryBuildLogsLog { return v.BuildLogs }

type Builder string

const (
	BuilderHeroku   Builder = "HEROKU"
	BuilderNixpacks Builder = "NIXPACKS"
	BuilderPaketo   Builder = "PAKETO"
	BuilderRailpack Builder = "RAILPACK"
)

var AllBuilder = []Builder{
	BuilderHeroku,
	BuilderNixpacks,
	BuilderPaketo,
	BuilderRailpack,
}

// DeploymentLogsQueryDeploymentLogsLog includes the requested fields of the GraphQL type Log.
// The GraphQL type's documentation follows.
//
// The result of a logs query.
type DeploymentLogsQueryDeploymentLogsLog struct {
	// The timestamp of the log message in format RFC3339 (nano)
	Timestamp string `json:"timestamp"`
	// The contents of the log message
	Message string `json:"message"`
	// The severity of the log message (eg. err)
	Severity *string `json:"severity"`
	// The attributes that were parsed from a structured log
	Attributes []DeploymentLogsQueryDeploymentLogsLogAttributesLogAttribute `json:"attributes"`
	// The tags that were associated with the log
	Tags *DeploymentLogsQueryDeploymentLogsLogTags `json:"tags"`
}

// GetTimestamp returns DeploymentLogsQueryDeploymentLogsLog.Timestamp, and is useful for accessing the field via an interface.
func (v *DeploymentLogsQueryDeploymentLogsLog) GetTimestamp() string { return v.Timestamp }

// GetMessage returns DeploymentLogsQueryDeploymentLogsLog.Message, and is useful for accessing the field via an interface.
func (v *DeploymentLogsQueryDeploymentLogsLog) GetMessage() string { return v.Message }

// GetSeverity returns DeploymentLogsQueryDeploymentLogsLog.Severity, and is useful for accessing the field via an interface.
func (v *DeploymentLogsQueryDeploymentLogsLog) GetSeverity() *string { return v.Severity }

// GetAttributes returns DeploymentLogsQueryDeploymentLogsLog.Attributes, and is useful for accessing the field via an interface.
func (v *DeploymentLogsQueryDeploymentLogsLog) GetAttributes() []DeploymentLogsQueryDeploymentLogsLogAttributesLogAttribute {
	return v.Attributes
}

// GetTags returns DeploymentLogsQueryDeploymentLogsLog.Tags, and is useful for accessing the field via an interface.
func (v *DeploymentLogsQueryDeploymentLogsLog) GetTags() *DeploymentLogsQueryDeploymentLogsLogTags {
	return v.Tags
}

// DeploymentLogsQueryDeploymentLogsLogAttributesLogAttribute includes the requested fields of the GraphQL type LogAttribute.
// The GraphQL type's documentation follows.
//
// The attributes associated with a structured log
type DeploymentLogsQueryDeploymentLogsLogAttributesLogAttribute struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// GetKey returns DeploymentLogsQueryDeploymentLogsLogAttributesLogAttribute.Key, and is useful for accessing the field via an interface.
func (v *DeploymentLogsQueryDeploymentLogsLogAttributesLogAttribute) GetKey() string { return v.Key }

// GetValue returns DeploymentLogsQueryDeploymentLogsLogAttributesLogAttribute.Value, and is useful for accessing the field via an interface.
func (v *DeploymentLogsQueryDeploymentLogsLogAttributesLogAttribute) GetValue() string {
	return v.Value
}

// DeploymentLogsQueryDeploymentLogsLogTags includes the requested fields of the GraphQL type LogTags.
// The GraphQL type's documentation follows.
//
// The tags associated with a specific log
type DeploymentLogsQueryDeploymentLogsLogTags struct {
	DeploymentId         *string `json:"deploymentId"`
	DeploymentInstanceId *string `json:"deploymentInstanceId"`
	ServiceId            *string `json:"serviceId"`
	ProjectId            *string `json:"projectId"`
	EnvironmentId        *string `json:"environmentId"`
}

// GetDeploymentId returns DeploymentLogsQueryDeploymentLogsLogTags.DeploymentId, and is useful for accessing the field via an interface.
func (v *DeploymentLogsQueryDeploymentLogsLogTags) GetDeploymentId() *string { return v.DeploymentId }

// GetDeploymentInstanceId returns DeploymentLogsQueryDeploymentLogsLogTags.DeploymentInstanceId, and is useful for accessing the field via an interface.
func (v *DeploymentLogsQueryDeploymentLogsLogTags) GetDeploymentInstanceId() *string {
	return v.DeploymentInstanceId
}

// GetServiceId returns DeploymentLogsQueryDeploymentLogsLogTags.ServiceId, and is useful for accessing the field via an interface.
func (v *DeploymentLogsQueryDeploymentLogsLogTags) GetServiceId() *string { return v.ServiceId }

// GetProjectId returns DeploymentLogsQueryDeploymentLogsLogTags.ProjectId, and is useful for accessing the field via an interface.
func (v *DeploymentLogsQueryDeploymentLogsLogTags) GetProjectId() *string { return v.ProjectId }

// GetEnvironmentId returns DeploymentLogsQueryDeploymentLogsLogTags.EnvironmentId, and is useful for accessing the field via an interface.
func (v *DeploymentLogsQueryDeploymentLogsLogTags) GetEnvironmentId() *string { return v.EnvironmentId }

// DeploymentLogsQueryResponse is returned by DeploymentLogsQuery on success.
type DeploymentLogsQueryResponse struct {
	// Fetch logs for a deployment
	DeploymentLogs []DeploymentLogsQueryDeploymentLogsLog `json:"deploymentLogs"`
}

// GetDeploymentLogs returns DeploymentLogsQueryResponse.DeploymentLogs, and is useful for accessing the field via an interface.
func (v *DeploymentLogsQueryResponse) GetDeploymentLogs() []DeploymentLogsQueryDeploymentLogsLog {
	return v.DeploymentLogs
}

type DeploymentStatus string

const (
	DeploymentStatusBuilding      DeploymentStatus = "BUILDING"
	DeploymentStatusCrashed       DeploymentStatus = "CRASHED"
	DeploymentStatusDeploying     DeploymentStatus = "DEPLOYING"
	DeploymentStatusFailed        DeploymentStatus = "FAILED"
	DeploymentStatusInitializing  DeploymentStatus = "INITIALIZING"
	DeploymentStatusNeedsApproval DeploymentStatus = "NEEDS_APPROVAL"
	DeploymentStatusQueued        DeploymentStatus = "QUEUED"
	DeploymentStatusRemoved       DeploymentStatus = "REMOVED"
	DeploymentStatusRemoving      DeploymentStatus = "REMOVING"
	DeploymentStatusSkipped       DeploymentStatus = "SKIPPED"
	DeploymentStatusSleeping      DeploymentStatus = "SLEEPING"
	DeploymentStatusSuccess       DeploymentStatus = "SUCCESS"
	DeploymentStatusWaiting       DeploymentStatus = "WAITING"
)

var AllDeploymentStatus = []DeploymentStatus{
	DeploymentStatusBuilding,
	DeploymentStatusCrashed,
	DeploymentStatusDeploying,
	DeploymentStatusFailed,
	DeploymentStatusInitializing,
	DeploymentStatusNeedsApproval,
	DeploymentStatusQueued,
	DeploymentStatusRemoved,
	DeploymentStatusRemoving,
	DeploymentStatusSkipped,
	DeploymentStatusSleeping,
	DeploymentStatusSuccess,
	DeploymentStatusWaiting,
}

// DeploymentsDeploymentsQueryDeploymentsConnection includes the requested fields of the GraphQL type QueryDeploymentsConnection.
type DeploymentsDeploymentsQueryDeploymentsConnection struct {
	Edges    []DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdge `json:"edges"`
	PageInfo DeploymentsDeploymentsQueryDeploymentsConnectionPageInfo                              `json:"pageInfo"`
}

// GetEdges returns DeploymentsDeploymentsQueryDeploymentsConnection.Edges, and is useful for accessing the field via an interface.
func (v *DeploymentsDeploymentsQueryDeploymentsConnection) GetEdges() []DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdge {
	return v.Edges
}

// GetPageInfo returns DeploymentsDeploymentsQueryDeploymentsConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *DeploymentsDeploymentsQueryDeploymentsConnection) GetPageInfo() DeploymentsDeploymentsQueryDeploymentsConnectionPageInfo {
	return v.PageInfo
}

// DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdge includes the requested fields of the GraphQL type QueryDeploymentsConnectionEdge.
type DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdge struct {
	Node DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment `json:"node"`
}

// GetNode returns DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdge.Node, and is useful for accessing the field via an interface.
func (v *DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdge) GetNode() DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment {
	return v.Node
}

// DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment includes the requested fields of the GraphQL type Deployment.
type DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment struct {
	Id            string           `json:"id"`
	Status        DeploymentStatus `json:"status"`
	CreatedAt     string           `json:"createdAt"`
	UpdatedAt     string           `json:"updatedAt"`
	StaticUrl     *string          `json:"staticUrl"`
	Url           *string          `json:"url"`
	Meta          *any             `json:"meta"`
	EnvironmentId string           `json:"environmentId"`
	ServiceId     *string          `json:"serviceId"`
	ProjectId     string           `json:"projectId"`
}

// GetId returns DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment.Id, and is useful for accessing the field via an interface.
func (v *DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment) GetId() string {
	return v.Id
}

// GetStatus returns DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment.Status, and is useful for accessing the field via an interface.
func (v *DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment) GetStatus() DeploymentStatus {
	return v.Status
}

// GetCreatedAt returns DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment.CreatedAt, and is useful for accessing the field via an interface.
func (v *DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment) GetCreatedAt() string {
	return v.CreatedAt
}

// GetUpdatedAt returns DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment.UpdatedAt, and is useful for accessing the field via an interface.
func (v *DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment) GetUpdatedAt() string {
	return v.UpdatedAt
}

// GetStaticUrl returns DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment.StaticUrl, and is useful for accessing the field via an interface.
func (v *DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment) GetStaticUrl() *string {
	return v.StaticUrl
}

// GetUrl returns DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment.Url, and is useful for accessing the field via an interface.
func (v *DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment) GetUrl() *string {
	return v.Url
}

// GetMeta returns DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment.Meta, and is useful for accessing the field via an interface.
func (v *DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment) GetMeta() *any {
	return v.Meta
}

// GetEnvironmentId returns DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment.EnvironmentId, and is useful for accessing the field via an interface.
func (v *DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment) GetEnvironmentId() string {
	return v.EnvironmentId
}

// GetServiceId returns DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment.ServiceId, and is useful for accessing the field via an interface.
func (v *DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment) GetServiceId() *string {
	return v.ServiceId
}

// GetProjectId returns DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment.ProjectId, and is useful for accessing the field via an interface.
func (v *DeploymentsDeploymentsQueryDeploymentsConnectionEdgesQueryDeploymentsConnectionEdgeNodeDeployment) GetProjectId() string {
	return v.ProjectId
}

// DeploymentsDeploymentsQueryDeploymentsConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
type DeploymentsDeploymentsQueryDeploymentsConnectionPageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor"`
}

// GetHasNextPage returns DeploymentsDeploymentsQueryDeploymentsConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *DeploymentsDeploymentsQueryDeploymentsConnectionPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

// GetEndCursor returns DeploymentsDeploymentsQueryDeploymentsConnectionPageInfo.EndCursor, and is useful for accessing the field via an interface.
func (v *DeploymentsDeploymentsQueryDeploymentsConnectionPageInfo) GetEndCursor() *string {
	return v.EndCursor
}

// DeploymentsResponse is returned by Deployments on success.
type DeploymentsResponse struct {
	// Get all deployments
	Deployments DeploymentsDeploymentsQueryDeploymentsConnection `json:"deployments"`
}

// GetDeployments returns DeploymentsResponse.Deployments, and is useful for accessing the field via an interface.
func (v *DeploymentsResponse) GetDeployments() DeploymentsDeploymentsQueryDeploymentsConnection {
	return v.Deployments
}

// EnvironmentLogsQueryEnvironmentLogsLog includes the requested fields of the GraphQL type Log.
// The GraphQL type's documentation follows.
//
// The result of a logs query.
type EnvironmentLogsQueryEnvironmentLogsLog struct {
	// The timestamp of the log message in format RFC3339 (nano)
	Timestamp string `json:"timestamp"`
	// The contents of the log message
	Message string `json:"message"`
	// The severity of the log message (eg. err)
	Severity *string `json:"severity"`
	// The attributes that were parsed from a structured log
	Attributes []EnvironmentLogsQueryEnvironmentLogsLogAttributesLogAttribute `json:"attributes"`
	// The tags that were associated with the log
	Tags *EnvironmentLogsQueryEnvironmentLogsLogTags `json:"tags"`
}

// GetTimestamp returns EnvironmentLogsQueryEnvironmentLogsLog.Timestamp, and is useful for accessing the field via an interface.
func (v *EnvironmentLogsQueryEnvironmentLogsLog) GetTimestamp() string { return v.Timestamp }

// GetMessage returns EnvironmentLogsQueryEnvironmentLogsLog.Message, and is useful for accessing the field via an interface.
func (v *EnvironmentLogsQueryEnvironmentLogsLog) GetMessage() string { return v.Message }

// GetSeverity returns EnvironmentLogsQueryEnvironmentLogsLog.Severity, and is useful for accessing the field via an interface.
func (v *EnvironmentLogsQueryEnvironmentLogsLog) GetSeverity() *string { return v.Severity }

// GetAttributes returns EnvironmentLogsQueryEnvironmentLogsLog.Attributes, and is useful for accessing the field via an interface.
func (v *EnvironmentLogsQueryEnvironmentLogsLog) GetAttributes() []EnvironmentLogsQueryEnvironmentLogsLogAttributesLogAttribute {
	return v.Attributes
}

// GetTags returns EnvironmentLogsQueryEnvironmentLogsLog.Tags, and is useful for accessing the field via an interface.
func (v *EnvironmentLogsQueryEnvironmentLogsLog) GetTags() *EnvironmentLogsQueryEnvironmentLogsLogTags {
	return v.Tags
}

// EnvironmentLogsQueryEnvironmentLogsLogAttributesLogAttribute includes the requested fields of the GraphQL type LogAttribute.
// The GraphQL type's documentation follows.
//
// The attributes associated with a structured log
type EnvironmentLogsQueryEnvironmentLogsLogAttributesLogAttribute struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// GetKey returns EnvironmentLogsQueryEnvironmentLogsLogAttributesLogAttribute.Key, and is useful for accessing the field via an interface.
func (v *EnvironmentLogsQueryEnvironmentLogsLogAttributesLogAttribute) GetKey() string { return v.Key }

// GetValue returns EnvironmentLogsQueryEnvironmentLogsLogAttributesLogAttribute.Value, and is useful for accessing the field via an interface.
func (v *EnvironmentLogsQueryEnvironmentLogsLogAttributesLogAttribute) GetValue() string {
	return v.Value
}

// EnvironmentLogsQueryEnvironmentLogsLogTags includes the requested fields of the GraphQL type LogTags.
// The GraphQL type's documentation follows.
//
// The tags associated with a specific log
type EnvironmentLogsQueryEnvironmentLogsLogTags struct {
	DeploymentId         *string `json:"deploymentId"`
	DeploymentInstanceId *string `json:"deploymentInstanceId"`
	ServiceId            *string `json:"serviceId"`
	ProjectId            *string `json:"projectId"`
	EnvironmentId        *string `json:"environmentId"`
}

// GetDeploymentId returns EnvironmentLogsQueryEnvironmentLogsLogTags.DeploymentId, and is useful for accessing the field via an interface.
func (v *EnvironmentLogsQueryEnvironmentLogsLogTags) GetDeploymentId() *string { return v.DeploymentId }

// GetDeploymentInstanceId returns EnvironmentLogsQueryEnvironmentLogsLogTags.DeploymentInstanceId, and is useful for accessing the field via an interface.
func (v *EnvironmentLogsQueryEnvironmentLogsLogTags) GetDeploymentInstanceId() *string {
	return v.DeploymentInstanceId
}

// GetServiceId returns EnvironmentLogsQueryEnvironmentLogsLogTags.ServiceId, and is useful for accessing the field via an interface.
func (v *EnvironmentLogsQueryEnvironmentLogsLogTags) GetServiceId() *string { return v.ServiceId }

// GetProjectId returns EnvironmentLogsQueryEnvironmentLogsLogTags.ProjectId, and is useful for accessing the field via an interface.
func (v *EnvironmentLogsQueryEnvironmentLogsLogTags) GetProjectId() *string { return v.ProjectId }

// GetEnvironmentId returns EnvironmentLogsQueryEnvironmentLogsLogTags.EnvironmentId, and is useful for accessing the field via an interface.
func (v *EnvironmentLogsQueryEnvironmentLogsLogTags) GetEnvironmentId() *string {
	return v.EnvironmentId
}

// EnvironmentLogsQueryResponse is returned by EnvironmentLogsQuery on success.
type EnvironmentLogsQueryResponse struct {
	// Fetch logs for a project environment. Build logs are excluded unless a snapshot ID is explicitly provided in the filter
	EnvironmentLogs []EnvironmentLogsQueryEnvironmentLogsLog `json:"environmentLogs"`
}

// GetEnvironmentLogs returns EnvironmentLogsQueryResponse.EnvironmentLogs, and is useful for accessing the field via an interface.
func (v *EnvironmentLogsQueryResponse) GetEnvironmentLogs() []EnvironmentLogsQueryEnvironmentLogsLog {
	return v.EnvironmentLogs
}

// EstimatedUsageEstimatedUsage includes the requested fields of the GraphQL type EstimatedUsage.
// The GraphQL type's documentation follows.
//
// The estimated usage of a single measurement.
type EstimatedUsageEstimatedUsage struct {
	// The estimated value.
	EstimatedValue float64 `json:"estimatedValue"`
	// The measurement that was estimated.
	Measurement MetricMeasurement `json:"measurement"`
	ProjectId   string            `json:"projectId"`
}

// GetEstimatedValue returns EstimatedUsageEstimatedUsage.EstimatedValue, and is useful for accessing the field via an interface.
func (v *EstimatedUsageEstimatedUsage) GetEstimatedValue() float64 { return v.EstimatedValue }

// GetMeasurement returns EstimatedUsageEstimatedUsage.Measurement, and is useful for accessing the field via an interface.
func (v *EstimatedUsageEstimatedUsage) GetMeasurement() MetricMeasurement { return v.Measurement }

// GetProjectId returns EstimatedUsageEstimatedUsage.ProjectId, and is useful for accessing the field via an interface.
func (v *EstimatedUsageEstimatedUsage) GetProjectId() string { return v.ProjectId }

// EstimatedUsageResponse is returned by EstimatedUsage on success.
type EstimatedUsageResponse struct {
	// Get the estimated total cost of the project at the end of the current billing
	// cycle. If no `startDate` is provided, the usage for the current billing period
	// of the project owner is returned.
	EstimatedUsage []EstimatedUsageEstimatedUsage `json:"estimatedUsage"`
}

// GetEstimatedUsage returns EstimatedUsageResponse.EstimatedUsage, and is useful for accessing the field via an interface.
func (v *EstimatedUsageResponse) GetEstimatedUsage() []EstimatedUsageEstimatedUsage {
	return v.EstimatedUsage
}

// HttpLogsQueryHttpLogsHttpLog includes the requested fields of the GraphQL type HttpLog.
// The GraphQL type's documentation follows.
//
// The result of a http logs query.
type HttpLogsQueryHttpLogsHttpLog struct {
	// The timestamp the log was created
	Timestamp string `json:"timestamp"`
	// The unique request ID
	RequestId string `json:"requestId"`
	// The request HTTP method
	Method string `json:"method"`
	// The requested path
	Path string `json:"path"`
	// The requested host
	Host string `json:"host"`
	// The http status of the log
	HttpStatus int `json:"httpStatus"`
	// The total duration the request took
	TotalDuration int `json:"totalDuration"`
	// How long the upstream request took to respond
	UpstreamRqDuration int `json:"upstreamRqDuration"`
	// The source IP of the request
	SrcIp string `json:"srcIp"`
	// The client user agent
	ClientUa string `json:"clientUa"`
	// Received bytes
	RxBytes int `json:"rxBytes"`
	// Outgoing bytes
	TxBytes int `json:"txBytes"`
	// The edge region the client connected to
	EdgeRegion string `json:"edgeRegion"`
	// The deployment ID that was requested
	DeploymentId string `json:"deploymentId"`
	// The deployment instance ID that was requested
	DeploymentInstanceId string `json:"deploymentInstanceId"`
	// The downstream HTTP protocol version
	DownstreamProto string `json:"downstreamProto"`
	// The upstream HTTP protocol version
	UpstreamProto string `json:"upstreamProto"`
	// The upstream address
	UpstreamAddress string `json:"upstreamAddress"`
	// Details about the upstream response
	ResponseDetails string `json:"responseDetails"`
	// Any upstream errors that occurred
	UpstreamErrors string `json:"upstreamErrors"`
}

// GetTimestamp returns HttpLogsQueryHttpLogsHttpLog.Timestamp, and is useful for accessing the field via an interface.
func (v *HttpLogsQueryHttpLogsHttpLog) GetTimestamp() string { return v.Timestamp }

// GetRequestId returns HttpLogsQueryHttpLogsHttpLog.RequestId, and is useful for accessing the field via an interface.
func (v *HttpLogsQueryHttpLogsHttpLog) GetRequestId() string { return v.RequestId }

// GetMethod returns HttpLogsQueryHttpLogsHttpLog.Method, and is useful for accessing the field via an interface.
func (v *HttpLogsQueryHttpLogsHttpLog) GetMethod() string { return v.Method }

// GetPath returns HttpLogsQueryHttpLogsHttpLog.Path, and is useful for accessing the field via an interface.
func (v *HttpLogsQueryHttpLogsHttpLog) GetPath() string { return v.Path }

// GetHost returns HttpLogsQueryHttpLogsHttpLog.Host, and is useful for accessing the field via an interface.
func (v *HttpLogsQueryHttpLogsHttpLog) GetHost() string { return v.Host }

// GetHttpStatus returns HttpLogsQueryHttpLogsHttpLog.HttpStatus, and is useful for accessing the field via an interface.
func (v *HttpLogsQueryHttpLogsHttpLog) GetHttpStatus() int { return v.HttpStatus }

// GetTotalDuration returns HttpLogsQueryHttpLogsHttpLog.TotalDuration, and is useful for accessing the field via an interface.
func (v *HttpLogsQueryHttpLogsHttpLog) GetTotalDuration() int { return v.TotalDuration }

// GetUpstreamRqDuration returns HttpLogsQueryHttpLogsHttpLog.UpstreamRqDuration, and is useful for accessing the field via an interface.
func (v *HttpLogsQueryHttpLogsHttpLog) GetUpstreamRqDuration() int { return v.UpstreamRqDuration }

// GetSrcIp returns HttpLogsQueryHttpLogsHttpLog.SrcIp, and is useful for accessing the field via an interface.
func (v *HttpLogsQueryHttpLogsHttpLog) GetSrcIp() string { return v.SrcIp }

// GetClientUa returns HttpLogsQueryHttpLogsHttpLog.ClientUa, and is useful for accessing the field via an interface.
func (v *HttpLogsQueryHttpLogsHttpLog) GetClientUa() string { return v.ClientUa }

// GetRxBytes returns HttpLogsQueryHttpLogsHttpLog.RxBytes, and is useful for accessing the field via an interface.
func (v *HttpLogsQueryHttpLogsHttpLog) GetRxBytes() int { return v.RxBytes }

// GetTxBytes returns HttpLogsQueryHttpLogsHttpLog.TxBytes, and is useful for accessing the field via an interface.
func (v *HttpLogsQueryHttpLogsHttpLog) GetTxBytes() int { return v.TxBytes }

// GetEdgeRegion returns HttpLogsQueryHttpLogsHttpLog.EdgeRegion, and is useful for accessing the field via an interface.
func (v *HttpLogsQueryHttpLogsHttpLog) GetEdgeRegion() string { return v.EdgeRegion }

// GetDeploymentId returns HttpLogsQueryHttpLogsHttpLog.DeploymentId, and is useful for accessing the field via an interface.
func (v *HttpLogsQueryHttpLogsHttpLog) GetDeploymentId() string { return v.DeploymentId }

// GetDeploymentInstanceId returns HttpLogsQueryHttpLogsHttpLog.DeploymentInstanceId, and is useful for accessing the field via an interface.
func (v *HttpLogsQueryHttpLogsHttpLog) GetDeploymentInstanceId() string {
	return v.DeploymentInstanceId
}

// GetDownstreamProto returns HttpLogsQueryHttpLogsHttpLog.DownstreamProto, and is useful for accessing the field via an interface.
func (v *HttpLogsQueryHttpLogsHttpLog) GetDownstreamProto() string { return v.DownstreamProto }

// GetUpstreamProto returns HttpLogsQueryHttpLogsHttpLog.UpstreamProto, and is useful for accessing the field via an interface.
func (v *HttpLogsQueryHttpLogsHttpLog) GetUpstreamProto() string { return v.UpstreamProto }

// GetUpstreamAddress returns HttpLogsQueryHttpLogsHttpLog.UpstreamAddress, and is useful for accessing the field via an interface.
func (v *HttpLogsQueryHttpLogsHttpLog) GetUpstreamAddress() string { return v.UpstreamAddress }

// GetResponseDetails returns HttpLogsQueryHttpLogsHttpLog.ResponseDetails, and is useful for accessing the field via an interface.
func (v *HttpLogsQueryHttpLogsHttpLog) GetResponseDetails() string { return v.ResponseDetails }

// GetUpstreamErrors returns HttpLogsQueryHttpLogsHttpLog.UpstreamErrors, and is useful for accessing the field via an interface.
func (v *HttpLogsQueryHttpLogsHttpLog) GetUpstreamErrors() string { return v.UpstreamErrors }

// HttpLogsQueryResponse is returned by HttpLogsQuery on success.
type HttpLogsQueryResponse struct {
	// Fetch HTTP logs for a deployment
	HttpLogs []HttpLogsQueryHttpLogsHttpLog `json:"httpLogs"`
}

// GetHttpLogs returns HttpLogsQueryResponse.HttpLogs, and is useful for accessing the field via an interface.
func (v *HttpLogsQueryResponse) GetHttpLogs() []HttpLogsQueryHttpLogsHttpLog { return v.HttpLogs }

// MeMeUser includes the requested fields of the GraphQL type User.
type MeMeUser struct {
	Id    string  `json:"id"`
	Name  *string `json:"name"`
	Email string  `json:"email"`
	// Workspaces user is member of
	Workspaces []MeMeUserWorkspacesWorkspace `json:"workspaces"`
}

// GetId returns MeMeUser.Id, and is useful for accessing the field via an interface.
func (v *MeMeUser) GetId() string { return v.Id }

// GetName returns MeMeUser.Name, and is useful for accessing the field via an interface.
func (v *MeMeUser) GetName() *string { return v.Name }

// GetEmail returns MeMeUser.Email, and is useful for accessing the field via an interface.
func (v *MeMeUser) GetEmail() string { return v.Email }

// GetWorkspaces returns MeMeUser.Workspaces, and is useful for accessing the field via an interface.
func (v *MeMeUser) GetWorkspaces() []MeMeUserWorkspacesWorkspace { return v.Workspaces }

// MeMeUserWorkspacesWorkspace includes the requested fields of the GraphQL type Workspace.
type MeMeUserWorkspacesWorkspace struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
}

// GetId returns MeMeUserWorkspacesWorkspace.Id, and is useful for accessing the field via an interface.
func (v *MeMeUserWorkspacesWorkspace) GetId() string { return v.Id }

// GetName returns MeMeUserWorkspacesWorkspace.Name, and is useful for accessing the field via an interface.
func (v *MeMeUserWorkspacesWorkspace) GetName() string { return v.Name }

// GetCreatedAt returns MeMeUserWorkspacesWorkspace.CreatedAt, and is useful for accessing the field via an interface.
func (v *MeMeUserWorkspacesWorkspace) GetCreatedAt() string { return v.CreatedAt }

// MeResponse is returned by Me on success.
type MeResponse struct {
	// Gets the authenticated user.
	Me MeMeUser `json:"me"`
}

// GetMe returns MeResponse.Me, and is useful for accessing the field via an interface.
func (v *MeResponse) GetMe() MeMeUser { return v.Me }

// A thing that can be measured on Railway.
type MetricMeasurement string

const (
	MetricMeasurementBackupUsageGb          MetricMeasurement = "BACKUP_USAGE_GB"
	MetricMeasurementCpuLimit               MetricMeasurement = "CPU_LIMIT"
	MetricMeasurementCpuUsage               MetricMeasurement = "CPU_USAGE"
	MetricMeasurementCpuUsage2              MetricMeasurement = "CPU_USAGE_2"
	MetricMeasurementDiskUsageGb            MetricMeasurement = "DISK_USAGE_GB"
	MetricMeasurementEphemeralDiskUsageGb   MetricMeasurement = "EPHEMERAL_DISK_USAGE_GB"
	MetricMeasurementMeasurementUnspecified MetricMeasurement = "MEASUREMENT_UNSPECIFIED"
	MetricMeasurementMemoryLimitGb          MetricMeasurement = "MEMORY_LIMIT_GB"
	MetricMeasurementMemoryUsageGb          MetricMeasurement = "MEMORY_USAGE_GB"
	MetricMeasurementNetworkRxGb            MetricMeasurement = "NETWORK_RX_GB"
	MetricMeasurementNetworkTxGb            MetricMeasurement = "NETWORK_TX_GB"
	MetricMeasurementUnrecognized           MetricMeasurement = "UNRECOGNIZED"
)

var AllMetricMeasurement = []MetricMeasurement{
	MetricMeasurementBackupUsageGb,
	MetricMeasurementCpuLimit,
	MetricMeasurementCpuUsage,
	MetricMeasurementCpuUsage2,
	MetricMeasurementDiskUsageGb,
	MetricMeasurementEphemeralDiskUsageGb,
	MetricMeasurementMeasurementUnspecified,
	MetricMeasurementMemoryLimitGb,
	MetricMeasurementMemoryUsageGb,
	MetricMeasurementNetworkRxGb,
	MetricMeasurementNetworkTxGb,
	MetricMeasurementUnrecognized,
}

// A property that can be used to group metrics.
type MetricTag string

const (
	MetricTagDeploymentId         MetricTag = "DEPLOYMENT_ID"
	MetricTagDeploymentInstanceId MetricTag = "DEPLOYMENT_INSTANCE_ID"
	MetricTagEnvironmentId        MetricTag = "ENVIRONMENT_ID"
	MetricTagHostType             MetricTag = "HOST_TYPE"
	MetricTagKeyUnspecified       MetricTag = "KEY_UNSPECIFIED"
	MetricTagPluginId             MetricTag = "PLUGIN_ID"
	MetricTagProjectId            MetricTag = "PROJECT_ID"
	MetricTagRegion               MetricTag = "REGION"
	MetricTagServiceId            MetricTag = "SERVICE_ID"
	MetricTagUnrecognized         MetricTag = "UNRECOGNIZED"
	MetricTagVolumeId             MetricTag = "VOLUME_ID"
	MetricTagVolumeInstanceId     MetricTag = "VOLUME_INSTANCE_ID"
)

var AllMetricTag = []MetricTag{
	MetricTagDeploymentId,
	MetricTagDeploymentInstanceId,
	MetricTagEnvironmentId,
	MetricTagHostType,
	MetricTagKeyUnspecified,
	MetricTagPluginId,
	MetricTagProjectId,
	MetricTagRegion,
	MetricTagServiceId,
	MetricTagUnrecognized,
	MetricTagVolumeId,
	MetricTagVolumeInstanceId,
}

// MetricsMetricsMetricsResult includes the requested fields of the GraphQL type MetricsResult.
// The GraphQL type's documentation follows.
//
// The result of a metrics query.
type MetricsMetricsMetricsResult struct {
	// The measurement of the metric.
	Measurement MetricMeasurement `json:"measurement"`
	// The tags that were used to group the metric. Only the tags that were used to by will be present.
	Tags MetricsMetricsMetricsResultTagsMetricTags `json:"tags"`
	// The samples of the metric.
	Values []MetricsMetricsMetricsResultValuesMetric `json:"values"`
}

// GetMeasurement returns MetricsMetricsMetricsResult.Measurement, and is useful for accessing the field via an interface.
func (v *MetricsMetricsMetricsResult) GetMeasurement() MetricMeasurement { return v.Measurement }

// GetTags returns MetricsMetricsMetricsResult.Tags, and is useful for accessing the field via an interface.
func (v *MetricsMetricsMetricsResult) GetTags() MetricsMetricsMetricsResultTagsMetricTags {
	return v.Tags
}

// GetValues returns MetricsMetricsMetricsResult.Values, and is useful for accessing the field via an interface.
func (v *MetricsMetricsMetricsResult) GetValues() []MetricsMetricsMetricsResultValuesMetric {
	return v.Values
}

// MetricsMetricsMetricsResultTagsMetricTags includes the requested fields of the GraphQL type MetricTags.
// The GraphQL type's documentation follows.
//
// The tags that were used to group the metric.
type MetricsMetricsMetricsResultTagsMetricTags struct {
	ProjectId            *string `json:"projectId"`
	ServiceId            *string `json:"serviceId"`
	EnvironmentId        *string `json:"environmentId"`
	DeploymentId         *string `json:"deploymentId"`
	DeploymentInstanceId *string `json:"deploymentInstanceId"`
	Region               *string `json:"region"`
}

// GetProjectId returns MetricsMetricsMetricsResultTagsMetricTags.ProjectId, and is useful for accessing the field via an interface.
func (v *MetricsMetricsMetricsResultTagsMetricTags) GetProjectId() *string { return v.ProjectId }

// GetServiceId returns MetricsMetricsMetricsResultTagsMetricTags.ServiceId, and is useful for accessing the field via an interface.
func (v *MetricsMetricsMetricsResultTagsMetricTags) GetServiceId() *string { return v.ServiceId }

// GetEnvironmentId returns MetricsMetricsMetricsResultTagsMetricTags.EnvironmentId, and is useful for accessing the field via an interface.
func (v *MetricsMetricsMetricsResultTagsMetricTags) GetEnvironmentId() *string {
	return v.EnvironmentId
}

// GetDeploymentId returns MetricsMetricsMetricsResultTagsMetricTags.DeploymentId, and is useful for accessing the field via an interface.
func (v *MetricsMetricsMetricsResultTagsMetricTags) GetDeploymentId() *string { return v.DeploymentId }

// GetDeploymentInstanceId returns MetricsMetricsMetricsResultTagsMetricTags.DeploymentInstanceId, and is useful for accessing the field via an interface.
func (v *MetricsMetricsMetricsResultTagsMetricTags) GetDeploymentInstanceId() *string {
	return v.DeploymentInstanceId
}

// GetRegion returns MetricsMetricsMetricsResultTagsMetricTags.Region, and is useful for accessing the field via an interface.
func (v *MetricsMetricsMetricsResultTagsMetricTags) GetRegion() *string { return v.Region }

// MetricsMetricsMetricsResultValuesMetric includes the requested fields of the GraphQL type Metric.
// The GraphQL type's documentation follows.
//
// A single sample of a metric.
type MetricsMetricsMetricsResultValuesMetric struct {
	// The timestamp of the sample. Represented has number of seconds since the Unix epoch.
	Ts int `json:"ts"`
	// The value of the sample.
	Value float64 `json:"value"`
}

// GetTs returns MetricsMetricsMetricsResultValuesMetric.Ts, and is useful for accessing the field via an interface.
func (v *MetricsMetricsMetricsResultValuesMetric) GetTs() int { return v.Ts }

// GetValue returns MetricsMetricsMetricsResultValuesMetric.Value, and is useful for accessing the field via an interface.
func (v *MetricsMetricsMetricsResultValuesMetric) GetValue() float64 { return v.Value }

// MetricsResponse is returned by Metrics on success.
type MetricsResponse struct {
	// Get metrics for a project, environment, and service
	Metrics []MetricsMetricsMetricsResult `json:"metrics"`
}

// GetMetrics returns MetricsResponse.Metrics, and is useful for accessing the field via an interface.
func (v *MetricsResponse) GetMetrics() []MetricsMetricsMetricsResult { return v.Metrics }

// ProjectsProjectsQueryProjectsConnection includes the requested fields of the GraphQL type QueryProjectsConnection.
type ProjectsProjectsQueryProjectsConnection struct {
	Edges []ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdge `json:"edges"`
}

// GetEdges returns ProjectsProjectsQueryProjectsConnection.Edges, and is useful for accessing the field via an interface.
func (v *ProjectsProjectsQueryProjectsConnection) GetEdges() []ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdge {
	return v.Edges
}

// ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdge includes the requested fields of the GraphQL type QueryProjectsConnectionEdge.
type ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdge struct {
	Node ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProject `json:"node"`
}

// GetNode returns ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdge.Node, and is useful for accessing the field via an interface.
func (v *ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdge) GetNode() ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProject {
	return v.Node
}

// ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProject includes the requested fields of the GraphQL type Project.
type ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProject struct {
	Id           string                                                                                                                      `json:"id"`
	Name         string                                                                                                                      `json:"name"`
	Description  *string                                                                                                                     `json:"description"`
	CreatedAt    string                                                                                                                      `json:"createdAt"`
	UpdatedAt    string                                                                                                                      `json:"updatedAt"`
	Environments ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectEnvironmentsProjectEnvironmentsConnection `json:"environments"`
	Services     ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnection         `json:"services"`
}

// GetId returns ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProject.Id, and is useful for accessing the field via an interface.
func (v *ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProject) GetId() string {
	return v.Id
}

// GetName returns ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProject.Name, and is useful for accessing the field via an interface.
func (v *ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProject) GetName() string {
	return v.Name
}

// GetDescription returns ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProject.Description, and is useful for accessing the field via an interface.
func (v *ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProject) GetDescription() *string {
	return v.Description
}

// GetCreatedAt returns ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProject.CreatedAt, and is useful for accessing the field via an interface.
func (v *ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProject) GetCreatedAt() string {
	return v.CreatedAt
}

// GetUpdatedAt returns ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProject.UpdatedAt, and is useful for accessing the field via an interface.
func (v *ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProject) GetUpdatedAt() string {
	return v.UpdatedAt
}

// GetEnvironments returns ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProject.Environments, and is useful for accessing the field via an interface.
func (v *ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProject) GetEnvironments() ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectEnvironmentsProjectEnvironmentsConnection {
	return v.Environments
}

// GetServices returns ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProject.Services, and is useful for accessing the field via an interface.
func (v *ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProject) GetServices() ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnection {
	return v.Services
}

// ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectEnvironmentsProjectEnvironmentsConnection includes the requested fields of the GraphQL type ProjectEnvironmentsConnection.
type ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectEnvironmentsProjectEnvironmentsConnection struct {
	Edges []ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectEnvironmentsProjectEnvironmentsConnectionEdgesProjectEnvironmentsConnectionEdge `json:"edges"`
}

// GetEdges returns ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectEnvironmentsProjectEnvironmentsConnection.Edges, and is useful for accessing the field via an interface.
func (v *ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectEnvironmentsProjectEnvironmentsConnection) GetEdges() []ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectEnvironmentsProjectEnvironmentsConnectionEdgesProjectEnvironmentsConnectionEdge {
	return v.Edges
}

// ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectEnvironmentsProjectEnvironmentsConnectionEdgesProjectEnvironmentsConnectionEdge includes the requested fields of the GraphQL type ProjectEnvironmentsConnectionEdge.
type ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectEnvironmentsProjectEnvironmentsConnectionEdgesProjectEnvironmentsConnectionEdge struct {
	Node ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectEnvironmentsProjectEnvironmentsConnectionEdgesProjectEnvironmentsConnectionEdgeNodeEnvironment `json:"node"`
}

// GetNode returns ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectEnvironmentsProjectEnvironmentsConnectionEdgesProjectEnvironmentsConnectionEdge.Node, and is useful for accessing the field via an interface.
func (v *ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectEnvironmentsProjectEnvironmentsConnectionEdgesProjectEnvironmentsConnectionEdge) GetNode() ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectEnvironmentsProjectEnvironmentsConnectionEdgesProjectEnvironmentsConnectionEdgeNodeEnvironment {
	return v.Node
}

// ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectEnvironmentsProjectEnvironmentsConnectionEdgesProjectEnvironmentsConnectionEdgeNodeEnvironment includes the requested fields of the GraphQL type Environment.
type ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectEnvironmentsProjectEnvironmentsConnectionEdgesProjectEnvironmentsConnectionEdgeNodeEnvironment struct {
	Id          string `json:"id"`
	Name        string `json:"name"`
	IsEphemeral bool   `json:"isEphemeral"`
}

// GetId returns ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectEnvironmentsProjectEnvironmentsConnectionEdgesProjectEnvironmentsConnectionEdgeNodeEnvironment.Id, and is useful for accessing the field via an interface.
func (v *ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectEnvironmentsProjectEnvironmentsConnectionEdgesProjectEnvironmentsConnectionEdgeNodeEnvironment) GetId() string {
	return v.Id
}

// GetName returns ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectEnvironmentsProjectEnvironmentsConnectionEdgesProjectEnvironmentsConnectionEdgeNodeEnvironment.Name, and is useful for accessing the field via an interface.
func (v *ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectEnvironmentsProjectEnvironmentsConnectionEdgesProjectEnvironmentsConnectionEdgeNodeEnvironment) GetName() string {
	return v.Name
}

// GetIsEphemeral returns ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectEnvironmentsProjectEnvironmentsConnectionEdgesProjectEnvironmentsConnectionEdgeNodeEnvironment.IsEphemeral, and is useful for accessing the field via an interface.
func (v *ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectEnvironmentsProjectEnvironmentsConnectionEdgesProjectEnvironmentsConnectionEdgeNodeEnvironment) GetIsEphemeral() bool {
	return v.IsEphemeral
}

// ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnection includes the requested fields of the GraphQL type ProjectServicesConnection.
type ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnection struct {
	Edges []ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnectionEdgesProjectServicesConnectionEdge `json:"edges"`
}

// GetEdges returns ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnection.Edges, and is useful for accessing the field via an interface.
func (v *ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnection) GetEdges() []ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnectionEdgesProjectServicesConnectionEdge {
	return v.Edges
}

// ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnectionEdgesProjectServicesConnectionEdge includes the requested fields of the GraphQL type ProjectServicesConnectionEdge.
type ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnectionEdgesProjectServicesConnectionEdge struct {
	Node ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnectionEdgesProjectServicesConnectionEdgeNodeService `json:"node"`
}

// GetNode returns ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnectionEdgesProjectServicesConnectionEdge.Node, and is useful for accessing the field via an interface.
func (v *ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnectionEdgesProjectServicesConnectionEdge) GetNode() ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnectionEdgesProjectServicesConnectionEdgeNodeService {
	return v.Node
}

// ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnectionEdgesProjectServicesConnectionEdgeNodeService includes the requested fields of the GraphQL type Service.
type ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnectionEdgesProjectServicesConnectionEdgeNodeService struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

// GetId returns ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnectionEdgesProjectServicesConnectionEdgeNodeService.Id, and is useful for accessing the field via an interface.
func (v *ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnectionEdgesProjectServicesConnectionEdgeNodeService) GetId() string {
	return v.Id
}

// GetName returns ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnectionEdgesProjectServicesConnectionEdgeNodeService.Name, and is useful for accessing the field via an interface.
func (v *ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnectionEdgesProjectServicesConnectionEdgeNodeService) GetName() string {
	return v.Name
}

// GetCreatedAt returns ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnectionEdgesProjectServicesConnectionEdgeNodeService.CreatedAt, and is useful for accessing the field via an interface.
func (v *ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnectionEdgesProjectServicesConnectionEdgeNodeService) GetCreatedAt() string {
	return v.CreatedAt
}

// GetUpdatedAt returns ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnectionEdgesProjectServicesConnectionEdgeNodeService.UpdatedAt, and is useful for accessing the field via an interface.
func (v *ProjectsProjectsQueryProjectsConnectionEdgesQueryProjectsConnectionEdgeNodeProjectServicesProjectServicesConnectionEdgesProjectServicesConnectionEdgeNodeService) GetUpdatedAt() string {
	return v.UpdatedAt
}

// ProjectsResponse is returned by Projects on success.
type ProjectsResponse struct {
	// Gets all projects for a user or workspace.
	Projects ProjectsProjectsQueryProjectsConnection `json:"projects"`
}

// GetProjects returns ProjectsResponse.Projects, and is useful for accessing the field via an interface.
func (v *ProjectsResponse) GetProjects() ProjectsProjectsQueryProjectsConnection { return v.Projects }

type RestartPolicyType string

const (
	RestartPolicyTypeAlways    RestartPolicyType = "ALWAYS"
	RestartPolicyTypeNever     RestartPolicyType = "NEVER"
	RestartPolicyTypeOnFailure RestartPolicyType = "ON_FAILURE"
)

var AllRestartPolicyType = []RestartPolicyType{
	RestartPolicyTypeAlways,
	RestartPolicyTypeNever,
	RestartPolicyTypeOnFailure,
}

// ServiceInstanceQueryResponse is returned by ServiceInstanceQuery on success.
type ServiceInstanceQueryResponse struct {
	// Get a service instance belonging to a service and environment
	ServiceInstance ServiceInstanceQueryServiceInstance `json:"serviceInstance"`
}

// GetServiceInstance returns ServiceInstanceQueryResponse.ServiceInstance, and is useful for accessing the field via an interface.
func (v *ServiceInstanceQueryResponse) GetServiceInstance() ServiceInstanceQueryServiceInstance {
	return v.ServiceInstance
}

// ServiceInstanceQueryServiceInstance includes the requested fields of the GraphQL type ServiceInstance.
type ServiceInstanceQueryServiceInstance struct {
	Id                      string                                               `json:"id"`
	ServiceId               string                                               `json:"serviceId"`
	ServiceName             string                                               `json:"serviceName"`
	EnvironmentId           string                                               `json:"environmentId"`
	StartCommand            *string                                              `json:"startCommand"`
	BuildCommand            *string                                              `json:"buildCommand"`
	HealthcheckPath         *string                                              `json:"healthcheckPath"`
	HealthcheckTimeout      *int                                                 `json:"healthcheckTimeout"`
	Region                  *string                                              `json:"region"`
	NumReplicas             *int                                                 `json:"numReplicas"`
	RestartPolicyType       RestartPolicyType                                    `json:"restartPolicyType"`
	RestartPolicyMaxRetries int                                                  `json:"restartPolicyMaxRetries"`
	CronSchedule            *string                                              `json:"cronSchedule"`
	SleepApplication        *bool                                                `json:"sleepApplication"`
	Builder                 Builder                                              `json:"builder"`
	Domains                 ServiceInstanceQueryServiceInstanceDomainsAllDomains `json:"domains"`
}

// GetId returns ServiceInstanceQueryServiceInstance.Id, and is useful for accessing the field via an interface.
func (v *ServiceInstanceQueryServiceInstance) GetId() string { return v.Id }

// GetServiceId returns ServiceInstanceQueryServiceInstance.ServiceId, and is useful for accessing the field via an interface.
func (v *ServiceInstanceQueryServiceInstance) GetServiceId() string { return v.ServiceId }

// GetServiceName returns ServiceInstanceQueryServiceInstance.ServiceName, and is useful for accessing the field via an interface.
func (v *ServiceInstanceQueryServiceInstance) GetServiceName() string { return v.ServiceName }

// GetEnvironmentId returns ServiceInstanceQueryServiceInstance.EnvironmentId, and is useful for accessing the field via an interface.
func (v *ServiceInstanceQueryServiceInstance) GetEnvironmentId() string { return v.EnvironmentId }

// GetStartCommand returns ServiceInstanceQueryServiceInstance.StartCommand, and is useful for accessing the field via an interface.
func (v *ServiceInstanceQueryServiceInstance) GetStartCommand() *string { return v.StartCommand }

// GetBuildCommand returns ServiceInstanceQueryServiceInstance.BuildCommand, and is useful for accessing the field via an interface.
func (v *ServiceInstanceQueryServiceInstance) GetBuildCommand() *string { return v.BuildCommand }

// GetHealthcheckPath returns ServiceInstanceQueryServiceInstance.HealthcheckPath, and is useful for accessing the field via an interface.
func (v *ServiceInstanceQueryServiceInstance) GetHealthcheckPath() *string { return v.HealthcheckPath }

// GetHealthcheckTimeout returns ServiceInstanceQueryServiceInstance.HealthcheckTimeout, and is useful for accessing the field via an interface.
func (v *ServiceInstanceQueryServiceInstance) GetHealthcheckTimeout() *int {
	return v.HealthcheckTimeout
}

// GetRegion returns ServiceInstanceQueryServiceInstance.Region, and is useful for accessing the field via an interface.
func (v *ServiceInstanceQueryServiceInstance) GetRegion() *string { return v.Region }

// GetNumReplicas returns ServiceInstanceQueryServiceInstance.NumReplicas, and is useful for accessing the field via an interface.
func (v *ServiceInstanceQueryServiceInstance) GetNumReplicas() *int { return v.NumReplicas }

// GetRestartPolicyType returns ServiceInstanceQueryServiceInstance.RestartPolicyType, and is useful for accessing the field via an interface.
func (v *ServiceInstanceQueryServiceInstance) GetRestartPolicyType() RestartPolicyType {
	return v.RestartPolicyType
}

// GetRestartPolicyMaxRetries returns ServiceInstanceQueryServiceInstance.RestartPolicyMaxRetries, and is useful for accessing the field via an interface.
func (v *ServiceInstanceQueryServiceInstance) GetRestartPolicyMaxRetries() int {
	return v.RestartPolicyMaxRetries
}

// GetCronSchedule returns ServiceInstanceQueryServiceInstance.CronSchedule, and is useful for accessing the field via an interface.
func (v *ServiceInstanceQueryServiceInstance) GetCronSchedule() *string { return v.CronSchedule }

// GetSleepApplication returns ServiceInstanceQueryServiceInstance.SleepApplication, and is useful for accessing the field via an interface.
func (v *ServiceInstanceQueryServiceInstance) GetSleepApplication() *bool { return v.SleepApplication }

// GetBuilder returns ServiceInstanceQueryServiceInstance.Builder, and is useful for accessing the field via an interface.
func (v *ServiceInstanceQueryServiceInstance) GetBuilder() Builder { return v.Builder }

// GetDomains returns ServiceInstanceQueryServiceInstance.Domains, and is useful for accessing the field via an interface.
func (v *ServiceInstanceQueryServiceInstance) GetDomains() ServiceInstanceQueryServiceInstanceDomainsAllDomains {
	return v.Domains
}

// ServiceInstanceQueryServiceInstanceDomainsAllDomains includes the requested fields of the GraphQL type AllDomains.
type ServiceInstanceQueryServiceInstanceDomainsAllDomains struct {
	CustomDomains  []ServiceInstanceQueryServiceInstanceDomainsAllDomainsCustomDomainsCustomDomain   `json:"customDomains"`
	ServiceDomains []ServiceInstanceQueryServiceInstanceDomainsAllDomainsServiceDomainsServiceDomain `json:"serviceDomains"`
}

// GetCustomDomains returns ServiceInstanceQueryServiceInstanceDomainsAllDomains.CustomDomains, and is useful for accessing the field via an interface.
func (v *ServiceInstanceQueryServiceInstanceDomainsAllDomains) GetCustomDomains() []ServiceInstanceQueryServiceInstanceDomainsAllDomainsCustomDomainsCustomDomain {
	return v.CustomDomains
}

// GetServiceDomains returns ServiceInstanceQueryServiceInstanceDomainsAllDomains.ServiceDomains, and is useful for accessing the field via an interface.
func (v *ServiceInstanceQueryServiceInstanceDomainsAllDomains) GetServiceDomains() []ServiceInstanceQueryServiceInstanceDomainsAllDomainsServiceDomainsServiceDomain {
	return v.ServiceDomains
}

// ServiceInstanceQueryServiceInstanceDomainsAllDomainsCustomDomainsCustomDomain includes the requested fields of the GraphQL type CustomDomain.
type ServiceInstanceQueryServiceInstanceDomainsAllDomainsCustomDomainsCustomDomain struct {
	Id     string `json:"id"`
	Domain string `json:"domain"`
}

// GetId returns ServiceInstanceQueryServiceInstanceDomainsAllDomainsCustomDomainsCustomDomain.Id, and is useful for accessing the field via an interface.
func (v *ServiceInstanceQueryServiceInstanceDomainsAllDomainsCustomDomainsCustomDomain) GetId() string {
	return v.Id
}

// GetDomain returns ServiceInstanceQueryServiceInstanceDomainsAllDomainsCustomDomainsCustomDomain.Domain, and is useful for accessing the field via an interface.
func (v *ServiceInstanceQueryServiceInstanceDomainsAllDomainsCustomDomainsCustomDomain) GetDomain() string {
	return v.Domain
}

// ServiceInstanceQueryServiceInstanceDomainsAllDomainsServiceDomainsServiceDomain includes the requested fields of the GraphQL type ServiceDomain.
type ServiceInstanceQueryServiceInstanceDomainsAllDomainsServiceDomainsServiceDomain struct {
	Id     string `json:"id"`
	Domain string `json:"domain"`
}

// GetId returns ServiceInstanceQueryServiceInstanceDomainsAllDomainsServiceDomainsServiceDomain.Id, and is useful for accessing the field via an interface.
func (v *ServiceInstanceQueryServiceInstanceDomainsAllDomainsServiceDomainsServiceDomain) GetId() string {
	return v.Id
}

// GetDomain returns ServiceInstanceQueryServiceInstanceDomainsAllDomainsServiceDomainsServiceDomain.Domain, and is useful for accessing the field via an interface.
func (v *ServiceInstanceQueryServiceInstanceDomainsAllDomainsServiceDomainsServiceDomain) GetDomain() string {
	return v.Domain
}

// TcpProxiesQueryResponse is returned by TcpProxiesQuery on success.
type TcpProxiesQueryResponse struct {
	// All TCP proxies for a service instance
	TcpProxies []TcpProxiesQueryTcpProxiesTCPProxy `json:"tcpProxies"`
}

// GetTcpProxies returns TcpProxiesQueryResponse.TcpProxies, and is useful for accessing the field via an interface.
func (v *TcpProxiesQueryResponse) GetTcpProxies() []TcpProxiesQueryTcpProxiesTCPProxy {
	return v.TcpProxies
}

// TcpProxiesQueryTcpProxiesTCPProxy includes the requested fields of the GraphQL type TCPProxy.
type TcpProxiesQueryTcpProxiesTCPProxy struct {
	Id              string  `json:"id"`
	Domain          string  `json:"domain"`
	ProxyPort       int     `json:"proxyPort"`
	ApplicationPort int     `json:"applicationPort"`
	EnvironmentId   string  `json:"environmentId"`
	ServiceId       string  `json:"serviceId"`
	CreatedAt       *string `json:"createdAt"`
	UpdatedAt       *string `json:"updatedAt"`
}

// GetId returns TcpProxiesQueryTcpProxiesTCPProxy.Id, and is useful for accessing the field via an interface.
func (v *TcpProxiesQueryTcpProxiesTCPProxy) GetId() string { return v.Id }

// GetDomain returns TcpProxiesQueryTcpProxiesTCPProxy.Domain, and is useful for accessing the field via an interface.
func (v *TcpProxiesQueryTcpProxiesTCPProxy) GetDomain() string { return v.Domain }

// GetProxyPort returns TcpProxiesQueryTcpProxiesTCPProxy.ProxyPort, and is useful for accessing the field via an interface.
func (v *TcpProxiesQueryTcpProxiesTCPProxy) GetProxyPort() int { return v.ProxyPort }

// GetApplicationPort returns TcpProxiesQueryTcpProxiesTCPProxy.ApplicationPort, and is useful for accessing the field via an interface.
func (v *TcpProxiesQueryTcpProxiesTCPProxy) GetApplicationPort() int { return v.ApplicationPort }

// GetEnvironmentId returns TcpProxiesQueryTcpProxiesTCPProxy.EnvironmentId, and is useful for accessing the field via an interface.
func (v *TcpProxiesQueryTcpProxiesTCPProxy) GetEnvironmentId() string { return v.EnvironmentId }

// GetServiceId returns TcpProxiesQueryTcpProxiesTCPProxy.ServiceId, and is useful for accessing the field via an interface.
func (v *TcpProxiesQueryTcpProxiesTCPProxy) GetServiceId() string { return v.ServiceId }

// GetCreatedAt returns TcpProxiesQueryTcpProxiesTCPProxy.CreatedAt, and is useful for accessing the field via an interface.
func (v *TcpProxiesQueryTcpProxiesTCPProxy) GetCreatedAt() *string { return v.CreatedAt }

// GetUpdatedAt returns TcpProxiesQueryTcpProxiesTCPProxy.UpdatedAt, and is useful for accessing the field via an interface.
func (v *TcpProxiesQueryTcpProxiesTCPProxy) GetUpdatedAt() *string { return v.UpdatedAt }

// UsageResponse is returned by Usage on success.
type UsageResponse struct {
	// Get the usage for a single project or all projects for a user/workspace. If no
	// `projectId` or `workspaceId` is provided, the usage for the current user is
	// returned. If no `startDate` is provided, the usage for the current billing
	// period of the project owner is returned.
	Usage []UsageUsageAggregatedUsage `json:"usage"`
}

// GetUsage returns UsageResponse.Usage, and is useful for accessing the field via an interface.
func (v *UsageResponse) GetUsage() []UsageUsageAggregatedUsage { return v.Usage }

// UsageUsageAggregatedUsage includes the requested fields of the GraphQL type AggregatedUsage.
// The GraphQL type's documentation follows.
//
// The aggregated usage of a single measurement.
type UsageUsageAggregatedUsage struct {
	// The measurement that was aggregated.
	Measurement MetricMeasurement `json:"measurement"`
	// The tags that were used to group the metric. Only the tags that were used in the `groupBy` will be present.
	Tags UsageUsageAggregatedUsageTagsMetricTags `json:"tags"`
	// The aggregated value.
	Value float64 `json:"value"`
}

// GetMeasurement returns UsageUsageAggregatedUsage.Measurement, and is useful for accessing the field via an interface.
func (v *UsageUsageAggregatedUsage) GetMeasurement() MetricMeasurement { return v.Measurement }

// GetTags returns UsageUsageAggregatedUsage.Tags, and is useful for accessing the field via an interface.
func (v *UsageUsageAggregatedUsage) GetTags() UsageUsageAggregatedUsageTagsMetricTags { return v.Tags }

// GetValue returns UsageUsageAggregatedUsage.Value, and is useful for accessing the field via an interface.
func (v *UsageUsageAggregatedUsage) GetValue() float64 { return v.Value }

// UsageUsageAggregatedUsageTagsMetricTags includes the requested fields of the GraphQL type MetricTags.
// The GraphQL type's documentation follows.
//
// The tags that were used to group the metric.
type UsageUsageAggregatedUsageTagsMetricTags struct {
	ProjectId     *string `json:"projectId"`
	ServiceId     *string `json:"serviceId"`
	EnvironmentId *string `json:"environmentId"`
}

// GetProjectId returns UsageUsageAggregatedUsageTagsMetricTags.ProjectId, and is useful for accessing the field via an interface.
func (v *UsageUsageAggregatedUsageTagsMetricTags) GetProjectId() *string { return v.ProjectId }

// GetServiceId returns UsageUsageAggregatedUsageTagsMetricTags.ServiceId, and is useful for accessing the field via an interface.
func (v *UsageUsageAggregatedUsageTagsMetricTags) GetServiceId() *string { return v.ServiceId }

// GetEnvironmentId returns UsageUsageAggregatedUsageTagsMetricTags.EnvironmentId, and is useful for accessing the field via an interface.
func (v *UsageUsageAggregatedUsageTagsMetricTags) GetEnvironmentId() *string { return v.EnvironmentId }

// __BuildLogsQueryInput is used internally by genqlient
type __BuildLogsQueryInput struct {
	DeploymentId string  `json:"deploymentId"`
	Limit        *int    `json:"limit"`
	StartDate    *string `json:"startDate"`
	EndDate      *string `json:"endDate"`
	Filter       *string `json:"filter"`
}

// GetDeploymentId returns __BuildLogsQueryInput.DeploymentId, and is useful for accessing the field via an interface.
func (v *__BuildLogsQueryInput) GetDeploymentId() string { return v.DeploymentId }

// GetLimit returns __BuildLogsQueryInput.Limit, and is useful for accessing the field via an interface.
func (v *__BuildLogsQueryInput) GetLimit() *int { return v.Limit }

// GetStartDate returns __BuildLogsQueryInput.StartDate, and is useful for accessing the field via an interface.
func (v *__BuildLogsQueryInput) GetStartDate() *string { return v.StartDate }

// GetEndDate returns __BuildLogsQueryInput.EndDate, and is useful for accessing the field via an interface.
func (v *__BuildLogsQueryInput) GetEndDate() *string { return v.EndDate }

// GetFilter returns __BuildLogsQueryInput.Filter, and is useful for accessing the field via an interface.
func (v *__BuildLogsQueryInput) GetFilter() *string { return v.Filter }

// __DeploymentLogsQueryInput is used internally by genqlient
type __DeploymentLogsQueryInput struct {
	DeploymentId string  `json:"deploymentId"`
	Limit        *int    `json:"limit"`
	StartDate    *string `json:"startDate"`
	EndDate      *string `json:"endDate"`
	Filter       *string `json:"filter"`
}

// GetDeploymentId returns __DeploymentLogsQueryInput.DeploymentId, and is useful for accessing the field via an interface.
func (v *__DeploymentLogsQueryInput) GetDeploymentId() string { return v.DeploymentId }

// GetLimit returns __DeploymentLogsQueryInput.Limit, and is useful for accessing the field via an interface.
func (v *__DeploymentLogsQueryInput) GetLimit() *int { return v.Limit }

// GetStartDate returns __DeploymentLogsQueryInput.StartDate, and is useful for accessing the field via an interface.
func (v *__DeploymentLogsQueryInput) GetStartDate() *string { return v.StartDate }

// GetEndDate returns __DeploymentLogsQueryInput.EndDate, and is useful for accessing the field via an interface.
func (v *__DeploymentLogsQueryInput) GetEndDate() *string { return v.EndDate }

// GetFilter returns __DeploymentLogsQueryInput.Filter, and is useful for accessing the field via an interface.
func (v *__DeploymentLogsQueryInput) GetFilter() *string { return v.Filter }

// __DeploymentsInput is used internally by genqlient
type __DeploymentsInput struct {
	ProjectId     string  `json:"projectId"`
	EnvironmentId string  `json:"environmentId"`
	ServiceId     string  `json:"serviceId"`
	First         *int    `json:"first"`
	After         *string `json:"after"`
}

// GetProjectId returns __DeploymentsInput.ProjectId, and is useful for accessing the field via an interface.
func (v *__DeploymentsInput) GetProjectId() string { return v.ProjectId }

// GetEnvironmentId returns __DeploymentsInput.EnvironmentId, and is useful for accessing the field via an interface.
func (v *__DeploymentsInput) GetEnvironmentId() string { return v.EnvironmentId }

// GetServiceId returns __DeploymentsInput.ServiceId, and is useful for accessing the field via an interface.
func (v *__DeploymentsInput) GetServiceId() string { return v.ServiceId }

// GetFirst returns __DeploymentsInput.First, and is useful for accessing the field via an interface.
func (v *__DeploymentsInput) GetFirst() *int { return v.First }

// GetAfter returns __DeploymentsInput.After, and is useful for accessing the field via an interface.
func (v *__DeploymentsInput) GetAfter() *string { return v.After }

// __EnvironmentLogsQueryInput is used internally by genqlient
type __EnvironmentLogsQueryInput struct {
	EnvironmentId string  `json:"environmentId"`
	Filter        *string `json:"filter"`
	AfterDate     *string `json:"afterDate"`
	BeforeDate    *string `json:"beforeDate"`
	AfterLimit    *int    `json:"afterLimit"`
	BeforeLimit   *int    `json:"beforeLimit"`
	AnchorDate    *string `json:"anchorDate"`
}

// GetEnvironmentId returns __EnvironmentLogsQueryInput.EnvironmentId, and is useful for accessing the field via an interface.
func (v *__EnvironmentLogsQueryInput) GetEnvironmentId() string { return v.EnvironmentId }

// GetFilter returns __EnvironmentLogsQueryInput.Filter, and is useful for accessing the field via an interface.
func (v *__EnvironmentLogsQueryInput) GetFilter() *string { return v.Filter }

// GetAfterDate returns __EnvironmentLogsQueryInput.AfterDate, and is useful for accessing the field via an interface.
func (v *__EnvironmentLogsQueryInput) GetAfterDate() *string { return v.AfterDate }

// GetBeforeDate returns __EnvironmentLogsQueryInput.BeforeDate, and is useful for accessing the field via an interface.
func (v *__EnvironmentLogsQueryInput) GetBeforeDate() *string { return v.BeforeDate }

// GetAfterLimit returns __EnvironmentLogsQueryInput.AfterLimit, and is useful for accessing the field via an interface.
func (v *__EnvironmentLogsQueryInput) GetAfterLimit() *int { return v.AfterLimit }

// GetBeforeLimit returns __EnvironmentLogsQueryInput.BeforeLimit, and is useful for accessing the field via an interface.
func (v *__EnvironmentLogsQueryInput) GetBeforeLimit() *int { return v.BeforeLimit }

// GetAnchorDate returns __EnvironmentLogsQueryInput.AnchorDate, and is useful for accessing the field via an interface.
func (v *__EnvironmentLogsQueryInput) GetAnchorDate() *string { return v.AnchorDate }

// __EstimatedUsageInput is used internally by genqlient
type __EstimatedUsageInput struct {
	ProjectId    *string             `json:"projectId"`
	WorkspaceId  *string             `json:"workspaceId"`
	Measurements []MetricMeasurement `json:"measurements"`
}

// GetProjectId returns __EstimatedUsageInput.ProjectId, and is useful for accessing the field via an interface.
func (v *__EstimatedUsageInput) GetProjectId() *string { return v.ProjectId }

// GetWorkspaceId returns __EstimatedUsageInput.WorkspaceId, and is useful for accessing the field via an interface.
func (v *__EstimatedUsageInput) GetWorkspaceId() *string { return v.WorkspaceId }

// GetMeasurements returns __EstimatedUsageInput.Measurements, and is useful for accessing the field via an interface.
func (v *__EstimatedUsageInput) GetMeasurements() []MetricMeasurement { return v.Measurements }

// __HttpLogsQueryInput is used internally by genqlient
type __HttpLogsQueryInput struct {
	DeploymentId string  `json:"deploymentId"`
	Limit        *int    `json:"limit"`
	StartDate    *string `json:"startDate"`
	EndDate      *string `json:"endDate"`
	Filter       *string `json:"filter"`
}

// GetDeploymentId returns __HttpLogsQueryInput.DeploymentId, and is useful for accessing the field via an interface.
func (v *__HttpLogsQueryInput) GetDeploymentId() string { return v.DeploymentId }

// GetLimit returns __HttpLogsQueryInput.Limit, and is useful for accessing the field via an interface.
func (v *__HttpLogsQueryInput) GetLimit() *int { return v.Limit }

// GetStartDate returns __HttpLogsQueryInput.StartDate, and is useful for accessing the field via an interface.
func (v *__HttpLogsQueryInput) GetStartDate() *string { return v.StartDate }

// GetEndDate returns __HttpLogsQueryInput.EndDate, and is useful for accessing the field via an interface.
func (v *__HttpLogsQueryInput) GetEndDate() *string { return v.EndDate }

// GetFilter returns __HttpLogsQueryInput.Filter, and is useful for accessing the field via an interface.
func (v *__HttpLogsQueryInput) GetFilter() *string { return v.Filter }

// __MetricsInput is used internally by genqlient
type __MetricsInput struct {
	ProjectId              *string             `json:"projectId"`
	ServiceId              *string             `json:"serviceId"`
	EnvironmentId          *string             `json:"environmentId"`
	StartDate              string              `json:"startDate"`
	EndDate                *string             `json:"endDate"`
	Measurements           []MetricMeasurement `json:"measurements"`
	GroupBy                []MetricTag         `json:"groupBy"`
	SampleRateSeconds      *int                `json:"sampleRateSeconds"`
	AveragingWindowSeconds *int                `json:"averagingWindowSeconds"`
}

// GetProjectId returns __MetricsInput.ProjectId, and is useful for accessing the field via an interface.
func (v *__MetricsInput) GetProjectId() *string { return v.ProjectId }

// GetServiceId returns __MetricsInput.ServiceId, and is useful for accessing the field via an interface.
func (v *__MetricsInput) GetServiceId() *string { return v.ServiceId }

// GetEnvironmentId returns __MetricsInput.EnvironmentId, and is useful for accessing the field via an interface.
func (v *__MetricsInput) GetEnvironmentId() *string { return v.EnvironmentId }

// GetStartDate returns __MetricsInput.StartDate, and is useful for accessing the field via an interface.
func (v *__MetricsInput) GetStartDate() string { return v.StartDate }

// GetEndDate returns __MetricsInput.EndDate, and is useful for accessing the field via an interface.
func (v *__MetricsInput) GetEndDate() *string { return v.EndDate }

// GetMeasurements returns __MetricsInput.Measurements, and is useful for accessing the field via an interface.
func (v *__MetricsInput) GetMeasurements() []MetricMeasurement { return v.Measurements }

// GetGroupBy returns __MetricsInput.GroupBy, and is useful for accessing the field via an interface.
func (v *__MetricsInput) GetGroupBy() []MetricTag { return v.GroupBy }

// GetSampleRateSeconds returns __MetricsInput.SampleRateSeconds, and is useful for accessing the field via an interface.
func (v *__MetricsInput) GetSampleRateSeconds() *int { return v.SampleRateSeconds }

// GetAveragingWindowSeconds returns __MetricsInput.AveragingWindowSeconds, and is useful for accessing the field via an interface.
func (v *__MetricsInput) GetAveragingWindowSeconds() *int { return v.AveragingWindowSeconds }

// __ProjectsInput is used internally by genqlient
type __ProjectsInput struct {
	WorkspaceId *string `json:"workspaceId"`
}

// GetWorkspaceId returns __ProjectsInput.WorkspaceId, and is useful for accessing the field via an interface.
func (v *__ProjectsInput) GetWorkspaceId() *string { return v.WorkspaceId }

// __ServiceInstanceQueryInput is used internally by genqlient
type __ServiceInstanceQueryInput struct {
	EnvironmentId string `json:"environmentId"`
	ServiceId     string `json:"serviceId"`
}

// GetEnvironmentId returns __ServiceInstanceQueryInput.EnvironmentId, and is useful for accessing the field via an interface.
func (v *__ServiceInstanceQueryInput) GetEnvironmentId() string { return v.EnvironmentId }

// GetServiceId returns __ServiceInstanceQueryInput.ServiceId, and is useful for accessing the field via an interface.
func (v *__ServiceInstanceQueryInput) GetServiceId() string { return v.ServiceId }

// __TcpProxiesQueryInput is used internally by genqlient
type __TcpProxiesQueryInput struct {
	EnvironmentId string `json:"environmentId"`
	ServiceId     string `json:"serviceId"`
}

// GetEnvironmentId returns __TcpProxiesQueryInput.EnvironmentId, and is useful for accessing the field via an interface.
func (v *__TcpProxiesQueryInput) GetEnvironmentId() string { return v.EnvironmentId }

// GetServiceId returns __TcpProxiesQueryInput.ServiceId, and is useful for accessing the field via an interface.
func (v *__TcpProxiesQueryInput) GetServiceId() string { return v.ServiceId }

// __UsageInput is used internally by genqlient
type __UsageInput struct {
	ProjectId    *string             `json:"projectId"`
	WorkspaceId  *string             `json:"workspaceId"`
	Measurements []MetricMeasurement `json:"measurements"`
	GroupBy      []MetricTag         `json:"groupBy"`
	StartDate    *string             `json:"startDate"`
	EndDate      *string             `json:"endDate"`
}

// GetProjectId returns __UsageInput.ProjectId, and is useful for accessing the field via an interface.
func (v *__UsageInput) GetProjectId() *string { return v.ProjectId }

// GetWorkspaceId returns __UsageInput.WorkspaceId, and is useful for accessing the field via an interface.
func (v *__UsageInput) GetWorkspaceId() *string { return v.WorkspaceId }

// GetMeasurements returns __UsageInput.Measurements, and is useful for accessing the field via an interface.
func (v *__UsageInput) GetMeasurements() []MetricMeasurement { return v.Measurements }

// GetGroupBy returns __UsageInput.GroupBy, and is useful for accessing the field via an interface.
func (v *__UsageInput) GetGroupBy() []MetricTag { return v.GroupBy }

// GetStartDate returns __UsageInput.StartDate, and is useful for accessing the field via an interface.
func (v *__UsageInput) GetStartDate() *string { return v.StartDate }

// GetEndDate returns __UsageInput.EndDate, and is useful for accessing the field via an interface.
func (v *__UsageInput) GetEndDate() *string { return v.EndDate }

// The query executed by BuildLogsQuery.
const BuildLogsQuery_Operation = `
query BuildLogsQuery ($deploymentId: String!, $limit: Int, $startDate: DateTime, $endDate: DateTime, $filter: String) {
	buildLogs(deploymentId: $deploymentId, limit: $limit, startDate: $startDate, endDate: $endDate, filter: $filter) {
		timestamp
		message
		severity
		attributes {
			key
			value
		}
		tags {
			deploymentId
			deploymentInstanceId
			serviceId
			projectId
			environmentId
		}
	}
}
`

func BuildLogsQuery(
	ctx_ context.Context,
	client_ graphql.Client,
	deploymentId string,
	limit *int,
	startDate *string,
	endDate *string,
	filter *string,
) (data_ *BuildLogsQueryResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "BuildLogsQuery",
		Query:  BuildLogsQuery_Operation,
		Variables: &__BuildLogsQueryInput{
			DeploymentId: deploymentId,
			Limit:        limit,
			StartDate:    startDate,
			EndDate:      endDate,
			Filter:       filter,
		},
	}

	data_ = &BuildLogsQueryResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by DeploymentLogsQuery.
const DeploymentLogsQuery_Operation = `
query DeploymentLogsQuery ($deploymentId: String!, $limit: Int, $startDate: DateTime, $endDate: DateTime, $filter: String) {
	deploymentLogs(deploymentId: $deploymentId, limit: $limit, startDate: $startDate, endDate: $endDate, filter: $filter) {
		timestamp
		message
		severity
		attributes {
			key
			value
		}
		tags {
			deploymentId
			deploymentInstanceId
			serviceId
			projectId
			environmentId
		}
	}
}
`

func DeploymentLogsQuery(
	ctx_ context.Context,
	client_ graphql.Client,
	deploymentId string,
	limit *int,
	startDate *string,
	endDate *string,
	filter *string,
) (data_ *DeploymentLogsQueryResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "DeploymentLogsQuery",
		Query:  DeploymentLogsQuery_Operation,
		Variables: &__DeploymentLogsQueryInput{
			DeploymentId: deploymentId,
			Limit:        limit,
			StartDate:    startDate,
			EndDate:      endDate,
			Filter:       filter,
		},
	}

	data_ = &DeploymentLogsQueryResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by Deployments.
const Deployments_Operation = `
query Deployments ($projectId: String!, $environmentId: String!, $serviceId: String!, $first: Int, $after: String) {
	deployments(first: $first, after: $after, input: {projectId:$projectId,environmentId:$environmentId,serviceId:$serviceId}) {
		edges {
			node {
				id
				status
				createdAt
				updatedAt
				staticUrl
				url
				meta
				environmentId
				serviceId
				projectId
			}
		}
		pageInfo {
			hasNextPage
			endCursor
		}
	}
}
`

func Deployments(
	ctx_ context.Context,
	client_ graphql.Client,
	projectId string,
	environmentId string,
	serviceId string,
	first *int,
	after *string,
) (data_ *DeploymentsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "Deployments",
		Query:  Deployments_Operation,
		Variables: &__DeploymentsInput{
			ProjectId:     projectId,
			EnvironmentId: environmentId,
			ServiceId:     serviceId,
			First:         first,
			After:         after,
		},
	}

	data_ = &DeploymentsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by EnvironmentLogsQuery.
const EnvironmentLogsQuery_Operation = `
query EnvironmentLogsQuery ($environmentId: String!, $filter: String, $afterDate: String, $beforeDate: String, $afterLimit: Int, $beforeLimit: Int, $anchorDate: String) {
	environmentLogs(environmentId: $environmentId, filter: $filter, afterDate: $afterDate, beforeDate: $beforeDate, afterLimit: $afterLimit, beforeLimit: $beforeLimit, anchorDate: $anchorDate) {
		timestamp
		message
		severity
		attributes {
			key
			value
		}
		tags {
			deploymentId
			deploymentInstanceId
			serviceId
			projectId
			environmentId
		}
	}
}
`

func EnvironmentLogsQuery(
	ctx_ context.Context,
	client_ graphql.Client,
	environmentId string,
	filter *string,
	afterDate *string,
	beforeDate *string,
	afterLimit *int,
	beforeLimit *int,
	anchorDate *string,
) (data_ *EnvironmentLogsQueryResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "EnvironmentLogsQuery",
		Query:  EnvironmentLogsQuery_Operation,
		Variables: &__EnvironmentLogsQueryInput{
			EnvironmentId: environmentId,
			Filter:        filter,
			AfterDate:     afterDate,
			BeforeDate:    beforeDate,
			AfterLimit:    afterLimit,
			BeforeLimit:   beforeLimit,
			AnchorDate:    anchorDate,
		},
	}

	data_ = &EnvironmentLogsQueryResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by EstimatedUsage.
const EstimatedUsage_Operation = `
query EstimatedUsage ($projectId: String, $workspaceId: String, $measurements: [MetricMeasurement!]!) {
	estimatedUsage(projectId: $projectId, workspaceId: $workspaceId, measurements: $measurements) {
		estimatedValue
		measurement
		projectId
	}
}
`

func EstimatedUsage(
	ctx_ context.Context,
	client_ graphql.Client,
	projectId *string,
	workspaceId *string,
	measurements []MetricMeasurement,
) (data_ *EstimatedUsageResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "EstimatedUsage",
		Query:  EstimatedUsage_Operation,
		Variables: &__EstimatedUsageInput{
			ProjectId:    projectId,
			WorkspaceId:  workspaceId,
			Measurements: measurements,
		},
	}

	data_ = &EstimatedUsageResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by HttpLogsQuery.
const HttpLogsQuery_Operation = `
query HttpLogsQuery ($deploymentId: String!, $limit: Int, $startDate: String, $endDate: String, $filter: String) {
	httpLogs(deploymentId: $deploymentId, limit: $limit, startDate: $startDate, endDate: $endDate, filter: $filter) {
		timestamp
		requestId
		method
		path
		host
		httpStatus
		totalDuration
		upstreamRqDuration
		srcIp
		clientUa
		rxBytes
		txBytes
		edgeRegion
		deploymentId
		deploymentInstanceId
		downstreamProto
		upstreamProto
		upstreamAddress
		responseDetails
		upstreamErrors
	}
}
`

func HttpLogsQuery(
	ctx_ context.Context,
	client_ graphql.Client,
	deploymentId string,
	limit *int,
	startDate *string,
	endDate *string,
	filter *string,
) (data_ *HttpLogsQueryResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "HttpLogsQuery",
		Query:  HttpLogsQuery_Operation,
		Variables: &__HttpLogsQueryInput{
			DeploymentId: deploymentId,
			Limit:        limit,
			StartDate:    startDate,
			EndDate:      endDate,
			Filter:       filter,
		},
	}

	data_ = &HttpLogsQueryResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by Me.
const Me_Operation = `
query Me {
	me {
		id
		name
		email
		workspaces {
			id
			name
			createdAt
		}
	}
}
`

func Me(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *MeResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "Me",
		Query:  Me_Operation,
	}

	data_ = &MeResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by Metrics.
const Metrics_Operation = `
query Metrics ($projectId: String, $serviceId: String, $environmentId: String, $startDate: DateTime!, $endDate: DateTime, $measurements: [MetricMeasurement!]!, $groupBy: [MetricTag!], $sampleRateSeconds: Int, $averagingWindowSeconds: Int) {
	metrics(projectId: $projectId, serviceId: $serviceId, environmentId: $environmentId, startDate: $startDate, endDate: $endDate, measurements: $measurements, groupBy: $groupBy, sampleRateSeconds: $sampleRateSeconds, averagingWindowSeconds: $averagingWindowSeconds) {
		measurement
		tags {
			projectId
			serviceId
			environmentId
			deploymentId
			deploymentInstanceId
			region
		}
		values {
			ts
			value
		}
	}
}
`

func Metrics(
	ctx_ context.Context,
	client_ graphql.Client,
	projectId *string,
	serviceId *string,
	environmentId *string,
	startDate string,
	endDate *string,
	measurements []MetricMeasurement,
	groupBy []MetricTag,
	sampleRateSeconds *int,
	averagingWindowSeconds *int,
) (data_ *MetricsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "Metrics",
		Query:  Metrics_Operation,
		Variables: &__MetricsInput{
			ProjectId:              projectId,
			ServiceId:              serviceId,
			EnvironmentId:          environmentId,
			StartDate:              startDate,
			EndDate:                endDate,
			Measurements:           measurements,
			GroupBy:                groupBy,
			SampleRateSeconds:      sampleRateSeconds,
			AveragingWindowSeconds: averagingWindowSeconds,
		},
	}

	data_ = &MetricsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by Projects.
const Projects_Operation = `
query Projects ($workspaceId: String) {
	projects(first: 250, workspaceId: $workspaceId) {
		edges {
			node {
				id
				name
				description
				createdAt
				updatedAt
				environments {
					edges {
						node {
							id
							name
							isEphemeral
						}
					}
				}
				services {
					edges {
						node {
							id
							name
							createdAt
							updatedAt
						}
					}
				}
			}
		}
	}
}
`

func Projects(
	ctx_ context.Context,
	client_ graphql.Client,
	workspaceId *string,
) (data_ *ProjectsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "Projects",
		Query:  Projects_Operation,
		Variables: &__ProjectsInput{
			WorkspaceId: workspaceId,
		},
	}

	data_ = &ProjectsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by ServiceInstanceQuery.
const ServiceInstanceQuery_Operation = `
query ServiceInstanceQuery ($environmentId: String!, $serviceId: String!) {
	serviceInstance(environmentId: $environmentId, serviceId: $serviceId) {
		id
		serviceId
		serviceName
		environmentId
		startCommand
		buildCommand
		healthcheckPath
		healthcheckTimeout
		region
		numReplicas
		restartPolicyType
		restartPolicyMaxRetries
		cronSchedule
		sleepApplication
		builder
		domains {
			customDomains {
				id
				domain
			}
			serviceDomains {
				id
				domain
			}
		}
	}
}
`

func ServiceInstanceQuery(
	ctx_ context.Context,
	client_ graphql.Client,
	environmentId string,
	serviceId string,
) (data_ *ServiceInstanceQueryResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "ServiceInstanceQuery",
		Query:  ServiceInstanceQuery_Operation,
		Variables: &__ServiceInstanceQueryInput{
			EnvironmentId: environmentId,
			ServiceId:     serviceId,
		},
	}

	data_ = &ServiceInstanceQueryResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by TcpProxiesQuery.
const TcpProxiesQuery_Operation = `
query TcpProxiesQuery ($environmentId: String!, $serviceId: String!) {
	tcpProxies(environmentId: $environmentId, serviceId: $serviceId) {
		id
		domain
		proxyPort
		applicationPort
		environmentId
		serviceId
		createdAt
		updatedAt
	}
}
`

func TcpProxiesQuery(
	ctx_ context.Context,
	client_ graphql.Client,
	environmentId string,
	serviceId string,
) (data_ *TcpProxiesQueryResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "TcpProxiesQuery",
		Query:  TcpProxiesQuery_Operation,
		Variables: &__TcpProxiesQueryInput{
			EnvironmentId: environmentId,
			ServiceId:     serviceId,
		},
	}

	data_ = &TcpProxiesQueryResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by Usage.
const Usage_Operation = `
query Usage ($projectId: String, $workspaceId: String, $measurements: [MetricMeasurement!]!, $groupBy: [MetricTag!], $startDate: DateTime, $endDate: DateTime) {
	usage(projectId: $projectId, workspaceId: $workspaceId, measurements: $measurements, groupBy: $groupBy, startDate: $startDate, endDate: $endDate) {
		measurement
		tags {
			projectId
			serviceId
			environmentId
		}
		value
	}
}
`

func Usage(
	ctx_ context.Context,
	client_ graphql.Client,
	projectId *string,
	workspaceId *string,
	measurements []MetricMeasurement,
	groupBy []MetricTag,
	startDate *string,
	endDate *string,
) (data_ *UsageResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "Usage",
		Query:  Usage_Operation,
		Variables: &__UsageInput{
			ProjectId:    projectId,
			WorkspaceId:  workspaceId,
			Measurements: measurements,
			GroupBy:      groupBy,
			StartDate:    startDate,
			EndDate:      endDate,
		},
	}

	data_ = &UsageResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
