// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	json "encoding/json"
	reflect "reflect"
	time "time"

	collector "github.com/xevion/railway-collector/internal/collector"
	railway "github.com/xevion/railway-collector/internal/railway"
	gomock "go.uber.org/mock/gomock"
)

// MockRailwayAPI is a mock of RailwayAPI interface.
type MockRailwayAPI struct {
	ctrl     *gomock.Controller
	recorder *MockRailwayAPIMockRecorder
	isgomock struct{}
}

// MockRailwayAPIMockRecorder is the mock recorder for MockRailwayAPI.
type MockRailwayAPIMockRecorder struct {
	mock *MockRailwayAPI
}

// NewMockRailwayAPI creates a new mock instance.
func NewMockRailwayAPI(ctrl *gomock.Controller) *MockRailwayAPI {
	mock := &MockRailwayAPI{ctrl: ctrl}
	mock.recorder = &MockRailwayAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRailwayAPI) EXPECT() *MockRailwayAPIMockRecorder {
	return m.recorder
}

// GetDeployments mocks base method.
func (m *MockRailwayAPI) GetDeployments(ctx context.Context, projectID, envID, serviceID string, first *int, after *string) (*railway.DeploymentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeployments", ctx, projectID, envID, serviceID, first, after)
	ret0, _ := ret[0].(*railway.DeploymentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeployments indicates an expected call of GetDeployments.
func (mr *MockRailwayAPIMockRecorder) GetDeployments(ctx, projectID, envID, serviceID, first, after any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeployments", reflect.TypeOf((*MockRailwayAPI)(nil).GetDeployments), ctx, projectID, envID, serviceID, first, after)
}

// GetProjects mocks base method.
func (m *MockRailwayAPI) GetProjects(ctx context.Context, workspaceID *string) (*railway.ProjectsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjects", ctx, workspaceID)
	ret0, _ := ret[0].(*railway.ProjectsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjects indicates an expected call of GetProjects.
func (mr *MockRailwayAPIMockRecorder) GetProjects(ctx, workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjects", reflect.TypeOf((*MockRailwayAPI)(nil).GetProjects), ctx, workspaceID)
}

// GetServiceInstance mocks base method.
func (m *MockRailwayAPI) GetServiceInstance(ctx context.Context, envID, serviceID string) (*railway.ServiceInstanceQueryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceInstance", ctx, envID, serviceID)
	ret0, _ := ret[0].(*railway.ServiceInstanceQueryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceInstance indicates an expected call of GetServiceInstance.
func (mr *MockRailwayAPIMockRecorder) GetServiceInstance(ctx, envID, serviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceInstance", reflect.TypeOf((*MockRailwayAPI)(nil).GetServiceInstance), ctx, envID, serviceID)
}

// IsRateLimited mocks base method.
func (m *MockRailwayAPI) IsRateLimited() (bool, time.Duration) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRateLimited")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(time.Duration)
	return ret0, ret1
}

// IsRateLimited indicates an expected call of IsRateLimited.
func (mr *MockRailwayAPIMockRecorder) IsRateLimited() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRateLimited", reflect.TypeOf((*MockRailwayAPI)(nil).IsRateLimited))
}

// Me mocks base method.
func (m *MockRailwayAPI) Me(ctx context.Context) (*railway.MeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Me", ctx)
	ret0, _ := ret[0].(*railway.MeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Me indicates an expected call of Me.
func (mr *MockRailwayAPIMockRecorder) Me(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Me", reflect.TypeOf((*MockRailwayAPI)(nil).Me), ctx)
}

// RateLimitInfo mocks base method.
func (m *MockRailwayAPI) RateLimitInfo() (int, time.Time) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RateLimitInfo")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(time.Time)
	return ret0, ret1
}

// RateLimitInfo indicates an expected call of RateLimitInfo.
func (mr *MockRailwayAPIMockRecorder) RateLimitInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RateLimitInfo", reflect.TypeOf((*MockRailwayAPI)(nil).RateLimitInfo))
}

// RawQuery mocks base method.
func (m *MockRailwayAPI) RawQuery(ctx context.Context, operationName, query string, variables map[string]any) (*railway.RawQueryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RawQuery", ctx, operationName, query, variables)
	ret0, _ := ret[0].(*railway.RawQueryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RawQuery indicates an expected call of RawQuery.
func (mr *MockRailwayAPIMockRecorder) RawQuery(ctx, operationName, query, variables any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RawQuery", reflect.TypeOf((*MockRailwayAPI)(nil).RawQuery), ctx, operationName, query, variables)
}

// MockStateStore is a mock of StateStore interface.
type MockStateStore struct {
	ctrl     *gomock.Controller
	recorder *MockStateStoreMockRecorder
	isgomock struct{}
}

// MockStateStoreMockRecorder is the mock recorder for MockStateStore.
type MockStateStoreMockRecorder struct {
	mock *MockStateStore
}

// NewMockStateStore creates a new mock instance.
func NewMockStateStore(ctrl *gomock.Controller) *MockStateStore {
	mock := &MockStateStore{ctrl: ctrl}
	mock.recorder = &MockStateStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateStore) EXPECT() *MockStateStoreMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockStateStore) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockStateStoreMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStateStore)(nil).Close))
}

// DeleteDiscoveryCache mocks base method.
func (m *MockStateStore) DeleteDiscoveryCache(projectID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDiscoveryCache", projectID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDiscoveryCache indicates an expected call of DeleteDiscoveryCache.
func (mr *MockStateStoreMockRecorder) DeleteDiscoveryCache(projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDiscoveryCache", reflect.TypeOf((*MockStateStore)(nil).DeleteDiscoveryCache), projectID)
}

// GetCoverage mocks base method.
func (m *MockStateStore) GetCoverage(key string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCoverage", key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoverage indicates an expected call of GetCoverage.
func (mr *MockStateStoreMockRecorder) GetCoverage(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCoverage", reflect.TypeOf((*MockStateStore)(nil).GetCoverage), key)
}

// GetDiscoveryCache mocks base method.
func (m *MockStateStore) GetDiscoveryCache(projectID string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiscoveryCache", projectID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiscoveryCache indicates an expected call of GetDiscoveryCache.
func (mr *MockStateStoreMockRecorder) GetDiscoveryCache(projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiscoveryCache", reflect.TypeOf((*MockStateStore)(nil).GetDiscoveryCache), projectID)
}

// GetLogCursor mocks base method.
func (m *MockStateStore) GetLogCursor(deploymentID, logType string) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogCursor", deploymentID, logType)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GetLogCursor indicates an expected call of GetLogCursor.
func (mr *MockStateStoreMockRecorder) GetLogCursor(deploymentID, logType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogCursor", reflect.TypeOf((*MockStateStore)(nil).GetLogCursor), deploymentID, logType)
}

// GetMetricCursor mocks base method.
func (m *MockStateStore) GetMetricCursor(projectID string) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetricCursor", projectID)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GetMetricCursor indicates an expected call of GetMetricCursor.
func (mr *MockStateStoreMockRecorder) GetMetricCursor(projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetricCursor", reflect.TypeOf((*MockStateStore)(nil).GetMetricCursor), projectID)
}

// GetProjectListCache mocks base method.
func (m *MockStateStore) GetProjectListCache(workspaceID string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectListCache", workspaceID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProjectListCache indicates an expected call of GetProjectListCache.
func (mr *MockStateStoreMockRecorder) GetProjectListCache(workspaceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectListCache", reflect.TypeOf((*MockStateStore)(nil).GetProjectListCache), workspaceID)
}

// ListCoverage mocks base method.
func (m *MockStateStore) ListCoverage() (map[string][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCoverage")
	ret0, _ := ret[0].(map[string][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCoverage indicates an expected call of ListCoverage.
func (mr *MockStateStoreMockRecorder) ListCoverage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCoverage", reflect.TypeOf((*MockStateStore)(nil).ListCoverage))
}

// ListDiscoveryCache mocks base method.
func (m *MockStateStore) ListDiscoveryCache() (map[string][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDiscoveryCache")
	ret0, _ := ret[0].(map[string][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDiscoveryCache indicates an expected call of ListDiscoveryCache.
func (mr *MockStateStoreMockRecorder) ListDiscoveryCache() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDiscoveryCache", reflect.TypeOf((*MockStateStore)(nil).ListDiscoveryCache))
}

// SetCoverage mocks base method.
func (m *MockStateStore) SetCoverage(key string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCoverage", key, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCoverage indicates an expected call of SetCoverage.
func (mr *MockStateStoreMockRecorder) SetCoverage(key, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCoverage", reflect.TypeOf((*MockStateStore)(nil).SetCoverage), key, data)
}

// SetDiscoveryCache mocks base method.
func (m *MockStateStore) SetDiscoveryCache(projectID string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDiscoveryCache", projectID, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDiscoveryCache indicates an expected call of SetDiscoveryCache.
func (mr *MockStateStoreMockRecorder) SetDiscoveryCache(projectID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDiscoveryCache", reflect.TypeOf((*MockStateStore)(nil).SetDiscoveryCache), projectID, data)
}

// SetLogCursor mocks base method.
func (m *MockStateStore) SetLogCursor(deploymentID, logType string, ts time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLogCursor", deploymentID, logType, ts)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLogCursor indicates an expected call of SetLogCursor.
func (mr *MockStateStoreMockRecorder) SetLogCursor(deploymentID, logType, ts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLogCursor", reflect.TypeOf((*MockStateStore)(nil).SetLogCursor), deploymentID, logType, ts)
}

// SetMetricCursor mocks base method.
func (m *MockStateStore) SetMetricCursor(projectID string, ts time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMetricCursor", projectID, ts)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMetricCursor indicates an expected call of SetMetricCursor.
func (mr *MockStateStoreMockRecorder) SetMetricCursor(projectID, ts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMetricCursor", reflect.TypeOf((*MockStateStore)(nil).SetMetricCursor), projectID, ts)
}

// SetProjectListCache mocks base method.
func (m *MockStateStore) SetProjectListCache(workspaceID string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProjectListCache", workspaceID, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProjectListCache indicates an expected call of SetProjectListCache.
func (mr *MockStateStoreMockRecorder) SetProjectListCache(workspaceID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProjectListCache", reflect.TypeOf((*MockStateStore)(nil).SetProjectListCache), workspaceID, data)
}

// MockTargetProvider is a mock of TargetProvider interface.
type MockTargetProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTargetProviderMockRecorder
	isgomock struct{}
}

// MockTargetProviderMockRecorder is the mock recorder for MockTargetProvider.
type MockTargetProviderMockRecorder struct {
	mock *MockTargetProvider
}

// NewMockTargetProvider creates a new mock instance.
func NewMockTargetProvider(ctrl *gomock.Controller) *MockTargetProvider {
	mock := &MockTargetProvider{ctrl: ctrl}
	mock.recorder = &MockTargetProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTargetProvider) EXPECT() *MockTargetProviderMockRecorder {
	return m.recorder
}

// Refresh mocks base method.
func (m *MockTargetProvider) Refresh(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Refresh indicates an expected call of Refresh.
func (mr *MockTargetProviderMockRecorder) Refresh(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockTargetProvider)(nil).Refresh), ctx)
}

// Targets mocks base method.
func (m *MockTargetProvider) Targets() []collector.ServiceTarget {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Targets")
	ret0, _ := ret[0].([]collector.ServiceTarget)
	return ret0
}

// Targets indicates an expected call of Targets.
func (mr *MockTargetProviderMockRecorder) Targets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Targets", reflect.TypeOf((*MockTargetProvider)(nil).Targets))
}

// MockTaskGenerator is a mock of TaskGenerator interface.
type MockTaskGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockTaskGeneratorMockRecorder
	isgomock struct{}
}

// MockTaskGeneratorMockRecorder is the mock recorder for MockTaskGenerator.
type MockTaskGeneratorMockRecorder struct {
	mock *MockTaskGenerator
}

// NewMockTaskGenerator creates a new mock instance.
func NewMockTaskGenerator(ctrl *gomock.Controller) *MockTaskGenerator {
	mock := &MockTaskGenerator{ctrl: ctrl}
	mock.recorder = &MockTaskGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskGenerator) EXPECT() *MockTaskGeneratorMockRecorder {
	return m.recorder
}

// Deliver mocks base method.
func (m *MockTaskGenerator) Deliver(ctx context.Context, item collector.WorkItem, data json.RawMessage, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Deliver", ctx, item, data, err)
}

// Deliver indicates an expected call of Deliver.
func (mr *MockTaskGeneratorMockRecorder) Deliver(ctx, item, data, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deliver", reflect.TypeOf((*MockTaskGenerator)(nil).Deliver), ctx, item, data, err)
}

// NextPoll mocks base method.
func (m *MockTaskGenerator) NextPoll() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextPoll")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// NextPoll indicates an expected call of NextPoll.
func (mr *MockTaskGeneratorMockRecorder) NextPoll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextPoll", reflect.TypeOf((*MockTaskGenerator)(nil).NextPoll))
}

// Poll mocks base method.
func (m *MockTaskGenerator) Poll(now time.Time) []collector.WorkItem {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Poll", now)
	ret0, _ := ret[0].([]collector.WorkItem)
	return ret0
}

// Poll indicates an expected call of Poll.
func (mr *MockTaskGeneratorMockRecorder) Poll(now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Poll", reflect.TypeOf((*MockTaskGenerator)(nil).Poll), now)
}

// Type mocks base method.
func (m *MockTaskGenerator) Type() collector.TaskType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(collector.TaskType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockTaskGeneratorMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockTaskGenerator)(nil).Type))
}
